Repository hpcaitech/ColossalAI, pull requests merged in 2021-12, with the labels that each got.

#75 overlap computation and communication in 2d operations
  colossalai/nn/layer/parallel_2d/_operation.py
Labels: enhancement

#76 fixed zero level 3 dtype bug
  colossalai/amp/apex_amp/__init__.py
  colossalai/zero/__init__.py
  colossalai/zero/zero_redundancy_optimizer_level_3.py
  tests/test_zero_data_parallel/test_zero_level_3.py
  tests/test_zero_tensor_parallel/test_vit_2d_level_3.py
Labels: bug

#80 Add interleaved pipeline and fix naive amp
  colossalai/amp/naive_amp/__init__.py
  colossalai/amp/naive_amp/_fp16_optimizer.py
  colossalai/builder/__init__.py
  colossalai/builder/pipeline.py
  colossalai/communication/p2p.py
  colossalai/communication/utils.py
  colossalai/context/parallel_context.py
  colossalai/engine/gradient_handler/_data_parallel_gradient_handler.py
  colossalai/engine/schedule/__init__.py
  colossalai/engine/schedule/_pipeline_schedule.py
  colossalai/initialize.py
  colossalai/utils/__init__.py
  colossalai/utils/common.py
  docs/parallelization.md
  tests/test_data_pipeline_tensor_parallel/run_cifar10_vit2d_with_pipeline.py
  tests/test_trainer/test_pipeline/test_partition.py
  tests/test_trainer/test_pipeline/test_pipeline_schedule.py
Labels: bug, enhancement

#50 add example of self-supervised SimCLR training - V2
  examples/simclr_cifar10_data_parallel/NT_Xentloss.py
  examples/simclr_cifar10_data_parallel/README.md
  examples/simclr_cifar10_data_parallel/augmentation.py
  examples/simclr_cifar10_data_parallel/config.py
  examples/simclr_cifar10_data_parallel/le_config.py
  examples/simclr_cifar10_data_parallel/models/Backbone.py
  examples/simclr_cifar10_data_parallel/models/linear_eval.py
  examples/simclr_cifar10_data_parallel/models/simclr.py
  examples/simclr_cifar10_data_parallel/myhooks.py
  examples/simclr_cifar10_data_parallel/results/embedding.npz
  examples/simclr_cifar10_data_parallel/results/linear_eval_acc.png
  examples/simclr_cifar10_data_parallel/results/linear_eval_loss.png
  examples/simclr_cifar10_data_parallel/results/ssl_loss.png
  examples/simclr_cifar10_data_parallel/results/test_tsne.png
  examples/simclr_cifar10_data_parallel/results/train_tsne.png
  examples/simclr_cifar10_data_parallel/train.sh
  examples/simclr_cifar10_data_parallel/train_linear.py
  examples/simclr_cifar10_data_parallel/train_simclr.py
  examples/simclr_cifar10_data_parallel/visualization.py
Labels: documentation

#55 add colossalai kernel module
  colossalai/kernel/__init__.py
  colossalai/kernel/cuda_native/__init__.py
  colossalai/kernel/cuda_native/builder.py
  colossalai/kernel/cuda_native/csrc/compat.h
  colossalai/kernel/cuda_native/csrc/kernels/cross_entropy.cu
  colossalai/kernel/cuda_native/csrc/kernels/cublas_wrappers.cu
  colossalai/kernel/cuda_native/csrc/kernels/cuda_util.cu
  colossalai/kernel/cuda_native/csrc/kernels/dropout_kernels.cu
  colossalai/kernel/cuda_native/csrc/kernels/general_kernels.cu
  colossalai/kernel/cuda_native/csrc/kernels/include/block_reduce.h
  colossalai/kernel/cuda_native/csrc/kernels/include/context.h
  colossalai/kernel/cuda_native/csrc/kernels/include/cross_entropy_layer.h
  colossalai/kernel/cuda_native/csrc/kernels/include/cublas_wrappers.h
  colossalai/kernel/cuda_native/csrc/kernels/include/cuda_util.h
  colossalai/kernel/cuda_native/csrc/kernels/include/dropout.h
  colossalai/kernel/cuda_native/csrc/kernels/include/feed_forward.h
  colossalai/kernel/cuda_native/csrc/kernels/include/kernels.h
  colossalai/kernel/cuda_native/csrc/kernels/include/ls_cub.cuh
  colossalai/kernel/cuda_native/csrc/kernels/include/normalize_layer.h
  colossalai/kernel/cuda_native/csrc/kernels/include/softmax.h
  colossalai/kernel/cuda_native/csrc/kernels/include/strided_batch_gemm.h
  colossalai/kernel/cuda_native/csrc/kernels/normalize_kernels.cu
  colossalai/kernel/cuda_native/csrc/kernels/softmax_kernels.cu
  colossalai/kernel/cuda_native/csrc/kernels/transform_kernels.cu
  colossalai/kernel/cuda_native/csrc/layer_norm_cuda.cpp
  colossalai/kernel/cuda_native/csrc/layer_norm_cuda_kernel.cu
  colossalai/kernel/cuda_native/csrc/multihead_attention_1d.cpp
  colossalai/kernel/cuda_native/csrc/multihead_attention_1d.h
  colossalai/kernel/cuda_native/csrc/scaled_masked_softmax.cpp
  colossalai/kernel/cuda_native/csrc/scaled_masked_softmax.h
  colossalai/kernel/cuda_native/csrc/scaled_masked_softmax_cuda.cu
  colossalai/kernel/cuda_native/csrc/scaled_upper_triang_masked_softmax.cpp
  colossalai/kernel/cuda_native/csrc/scaled_upper_triang_masked_softmax.h
  colossalai/kernel/cuda_native/csrc/scaled_upper_triang_masked_softmax_cuda.cu
  colossalai/kernel/cuda_native/csrc/type_shim.h
  colossalai/kernel/cuda_native/layer_norm.py
  colossalai/kernel/cuda_native/multihead_attention.py
  colossalai/kernel/cuda_native/scaled_softmax.py
  colossalai/kernel/jit/__init__.py
  colossalai/kernel/jit/bias_dropout_add.py
  colossalai/kernel/jit/bias_gelu.py
  colossalai/kernel/jit/option.py
  setup.py
Labels: enhancement
