Repository hpcaitech/ColossalAI, pull requests merged in 2023-07, with the labels that each got.

#4144 [shardformer] made tensor parallelism configurable
  colossalai/shardformer/policies/basepolicy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/policies/bloom.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/opt.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/shard/shard_config.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_bert.py
  tests/test_shardformer/test_model/test_shard_bloom.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
  tests/test_shardformer/test_model/test_shard_llama.py
  tests/test_shardformer/test_model/test_shard_opt.py
  tests/test_shardformer/test_model/test_shard_t5.py
Labels: enhancement, shardformer

#4149 [shardformer] added development protocol for standardization
  colossalai/shardformer/README.md
  colossalai/shardformer/model/modeling_bert.py
  colossalai/shardformer/modeling/__init__.py
  colossalai/shardformer/modeling/bloom.py
  colossalai/shardformer/policies/bloom.py
Labels: documentation, shardformer

#4138 [zero]support no_sync method for zero1 plugin
  colossalai/booster/booster.py
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/booster/plugin/plugin_base.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  colossalai/booster/plugin/torch_fsdp_plugin.py
  colossalai/zero/low_level/low_level_optim.py
  tests/test_zero/test_low_level/test_grad_acc.py
Labels: API

#4155 [chat] removed cache file
  applications/Chat/coati/trainer/.sft.py.swp
Labels: shardformer

#4153 [zero] allow passing process group to zero12
  colossalai/zero/low_level/_utils.py
  colossalai/zero/low_level/low_level_optim.py
  tests/test_zero/test_low_level/test_zero_init.py
  tests/test_zero/test_low_level/test_zero_tp.py
Labels: API, compatibility

#4165 [cli] hotfix launch command for multi-nodes
  colossalai/cli/launcher/run.py
Labels: bug

#4159 [workflow] show test duration
  .github/workflows/build_on_pr.yml
  .github/workflows/build_on_schedule.yml
Labels: DevOps

#4162 [dtensor] fixed readme file name and removed deprecated file
  colossalai/tensor/d_tensor/README.md
  colossalai/tensor/d_tensor/d_tensor.py
Labels: bug

#4158 [shardformer] supported flash attention test dependency
  .github/workflows/build_on_schedule.yml
  requirements/requirements-test.txt
Labels: shardformer

#3476 [autoparallel] integrate 2-stage solver
  colossalai/_analyzer/fx/codegen.py
  colossalai/auto_parallel/checkpoint/ckpt_solver_base.py
  colossalai/auto_parallel/checkpoint/ckpt_solver_rotor.py
  colossalai/auto_parallel/passes/meta_info_prop.py
  colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py
  colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py
  tests/test_auto_parallel/test_tensor_shard/test_2stage_solver_on_gpt.py
  tests/test_auto_parallel/test_tensor_shard/test_2stage_solver_on_resnet.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_function_node.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_bias_linear_module_node.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_getitem_handler.py
Labels: auto-parallel

#4176 [pipeline] fit shardformer policy
  colossalai/shardformer/policies/auto_policy.py
  colossalai/shardformer/policies/base_policy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/policies/bloom.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/opt.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/policies/vit.py
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  colossalai/shardformer/shard/shardformer.py
  colossalai/shardformer/shard/utils.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_shard_utils.py
  tests/test_shardformer/test_with_torch_ddp.py
Labels: enhancement

#4179 [zero] add state dict for low level zero
  colossalai/zero/low_level/low_level_optim.py
  tests/test_zero/test_low_level/test_zero_ckpt.py
Labels: enhancement, compatibility

#4185 [shardformer] llama support flash attention
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/modeling/opt.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/opt.py
  tests/test_shardformer/test_model/test_shard_llama.py
Labels: enhancement, shardformer

#4191 [shardformer] gpt2 support flash attention.
  colossalai/shardformer/modeling/gpt2.py
  colossalai/shardformer/policies/gpt2.py
  tests/kit/model_zoo/transformers/gpt.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
Labels: enhancement, shardformer

#4202 [shardformer] support lazy init
  colossalai/lazy/lazy_init.py
  colossalai/shardformer/layer/embedding.py
  colossalai/shardformer/layer/linear.py
  colossalai/shardformer/layer/normalization.py
  colossalai/shardformer/layer/qkv_fused_linear.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/policies/bloom.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/opt.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/shard/sharder.py
  tests/test_shardformer/test_layer/test_embedding.py
  tests/test_shardformer/test_layer/test_layernorm.py
  tests/test_shardformer/test_layer/test_linear_1d.py
  tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
  tests/test_shardformer/test_layer/test_vocab_parallel_embedding_1d.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_bert.py
  tests/test_shardformer/test_model/test_shard_bloom.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
  tests/test_shardformer/test_model/test_shard_llama.py
  tests/test_shardformer/test_model/test_shard_opt.py
  tests/test_shardformer/test_model/test_shard_t5.py
  tests/test_shardformer/test_with_torch_ddp.py
Labels: enhancement

#4194 [zero] support shard optimizer state dict of zero
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/zero/low_level/low_level_optim.py
  colossalai/zero/low_level/readme.md
  tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
Labels: compatibility

#4227 [example] polish code and readme of llama
  examples/language/llama/README.md
  examples/language/llama/benchmark.py
  examples/language/llama/pretrain.py
Labels: example

#4229 [shardformer] fix base policy
  colossalai/shardformer/policies/base_policy.py
Labels: bug

#4231 [shardformer] support SAM
  colossalai/shardformer/_utils.py
  colossalai/shardformer/layer/__init__.py
  colossalai/shardformer/layer/qkv_fused_linear.py
  colossalai/shardformer/modeling/sam.py
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/sam.py
  tests/kit/model_zoo/transformers/__init__.py
  tests/kit/model_zoo/transformers/sam.py
  tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
  tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
  tests/test_shardformer/test_model/test_shard_sam.py
Labels: shardformer

#4234 [shardformer] update gpt2 to use coloattention.
  colossalai/shardformer/modeling/gpt2.py
Labels: enhancement, shardformer

#4226 [shardformer] update opt and llama to use coloattention.
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/modeling/opt.py
Labels: enhancement, shardformer

#4212 [shardformer] support whisper
  colossalai/shardformer/README.md
  colossalai/shardformer/layer/embedding.py
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/whisper.py
  tests/kit/model_zoo/transformers/__init__.py
  tests/kit/model_zoo/transformers/whisper.py
  tests/test_shardformer/test_model/test_shard_whisper.py
Labels: shardformer

#4221 [zero] optimize the optimizer step time
  colossalai/zero/low_level/low_level_optim.py
Labels: enhancement

#4269 [lazy] support init on cuda
  colossalai/lazy/lazy_init.py
  requirements/requirements-test.txt
  tests/test_lazy/lazy_init_utils.py
  tests/test_lazy/test_models.py
Labels: enhancement

#4288 [gemini] support gemini-dp
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/tensor/process_group.py
  colossalai/zero/gemini/chunk/chunk.py
  colossalai/zero/gemini/chunk/search_utils.py
  colossalai/zero/gemini/chunk/utils.py
  colossalai/zero/gemini/gemini_ddp.py
  examples/language/llama/benchmark.py
Labels: enhancement

#4236 [shardformer] shardformer support jit fused operator.
  colossalai/shardformer/README.md
  colossalai/shardformer/modeling/bert.py
  colossalai/shardformer/modeling/bloom.py
  colossalai/shardformer/modeling/gpt2.py
  colossalai/shardformer/modeling/jit.py
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/modeling/opt.py
  colossalai/shardformer/modeling/t5.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/policies/bloom.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/opt.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/shard/shard_config.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_bert.py
  tests/test_shardformer/test_model/test_shard_bloom.py
  tests/test_shardformer/test_model/test_shard_opt.py
  tests/test_shardformer/test_model/test_shard_t5.py
Labels: shardformer

#4299 [example] support flash attn 2 for llama
  examples/language/llama/attn.py
  examples/language/llama/benchmark.py
Labels: enhancement

#4305 [ci] support testmon core pkg change detection
  .github/workflows/build_on_pr.yml
Labels: DevOps

#4301 [shardformer] whisper support flash attention
  colossalai/shardformer/modeling/whisper.py
  colossalai/shardformer/policies/whisper.py
  tests/kit/model_zoo/transformers/whisper.py
  tests/test_shardformer/test_model/test_shard_whisper.py
Labels: enhancement, shardformer

#4284 [shardformer] support pipeline base vit model
  colossalai/shardformer/modeling/vit.py
  colossalai/shardformer/policies/auto_policy.py
  colossalai/shardformer/policies/vit.py
  tests/kit/model_zoo/transformers/__init__.py
  tests/kit/model_zoo/transformers/vit.py
  tests/test_shardformer/test_model/test_shard_vit.py
  tests/test_shardformer/test_model/test_shard_vit_pipeline.py
Labels: pipeline-parallel, shardformer

#4295 [plugin] add 3d parallel plugin
  .github/workflows/build_on_pr.yml
  colossalai/amp/naive_amp/mixed_precision_optimizer.py
  colossalai/booster/booster.py
  colossalai/booster/plugin/__init__.py
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  colossalai/booster/plugin/pp_plugin_base.py
  colossalai/pipeline/p2p.py
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/shard/sharder.py
  tests/test_booster/test_plugin/test_3d_plugin.py
Labels: enhancement
