Repository hpcaitech/ColossalAI, pull requests merged in 2023-10, with the labels that each got.

#4771 [Infer] Colossal-Inference serving example w/ TorchServe (single GPU case)
  examples/inference/serving/test_ci.sh
  examples/inference/serving/torch_serve/Colossal_Inference_Handler.py
  examples/inference/serving/torch_serve/README.md
  examples/inference/serving/torch_serve/config.properties
  examples/inference/serving/torch_serve/docker/Dockerfile
  examples/inference/serving/torch_serve/model-config.yaml
  examples/inference/serving/torch_serve/sample_text.txt
Labels: example

#4824 [checkpointio] hotfix torch 2.0 compatibility
  colossalai/checkpoint_io/utils.py
  colossalai/zero/gemini/gemini_optimizer.py
  tests/test_checkpoint_io/test_hybrid_parallel_plugin_checkpoint_io.py
Labels: bug

#4866 [doc] update advanced tutorials, training gpt with hybrid parallelism
  docs/sidebars.json
  docs/source/en/advanced_tutorials/train_gpt_using_hybrid_parallelism.md
  docs/source/en/advanced_tutorials/train_vit_using_pipeline_parallelism.md
  docs/source/en/advanced_tutorials/train_vit_with_hybrid_parallelism.md
  docs/source/zh-Hans/advanced_tutorials/train_gpt_using_hybrid_parallelism.md
  docs/source/zh-Hans/advanced_tutorials/train_vit_using_pipeline_parallelism.md
  docs/source/zh-Hans/advanced_tutorials/train_vit_with_hybrid_parallelism.md
Labels: documentation

#4872 [gemini] support amp o3 for gemini
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/nn/optimizer/cpu_adam.py
  colossalai/nn/optimizer/hybrid_adam.py
  colossalai/testing/comparison.py
  colossalai/zero/gemini/chunk/chunk.py
  colossalai/zero/gemini/chunk/manager.py
  colossalai/zero/gemini/gemini_ddp.py
  colossalai/zero/gemini/gemini_optimizer.py
  colossalai/zero/gemini/utils.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_checkpoint_io/test_gemini_torch_compability.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
Labels: enhancement

#4896 [kernel] support pure fp16 for cpu adam
  colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
  colossalai/kernel/cuda_native/csrc/cpu_adam.h
  colossalai/nn/optimizer/cpu_adam.py
  colossalai/nn/optimizer/hybrid_adam.py
  tests/test_optimizer/test_adam_kernel.py
  tests/test_optimizer/test_adam_optim.py
Labels: enhancement

#4919 [kernel] fix cpu adam kernel for pure fp16 and update tests
  colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
  colossalai/kernel/cuda_native/csrc/cpu_adam.h
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_optim.py
Labels: testing

#4921 [kernel] support pure fp16 for cpu adam and update gemini optim tests
  colossalai/kernel/cuda_native/csrc/cpu_adam.cpp
  colossalai/kernel/cuda_native/csrc/cpu_adam.h
  colossalai/nn/optimizer/cpu_adam.py
  colossalai/nn/optimizer/hybrid_adam.py
  tests/test_optimizer/test_adam_kernel.py
  tests/test_optimizer/test_adam_optim.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_optim.py
Labels: enhancement, testing

#4883 [shardformer] shardformer support falcon
  colossalai/shardformer/README.md
  colossalai/shardformer/modeling/falcon.py
  colossalai/shardformer/policies/auto_policy.py
  colossalai/shardformer/policies/falcon.py
  docs/source/en/features/shardformer.md
  docs/source/zh-Hans/features/shardformer.md
  tests/kit/model_zoo/transformers/__init__.py
  tests/kit/model_zoo/transformers/falcon.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_shardformer/test_model/test_shard_falcon.py
Labels: shardformer

#4936 [hotfix] fix torch 2.0 compatibility
  colossalai/legacy/context/parallel_context.py
  colossalai/legacy/tensor/process_group.py
  colossalai/shardformer/modeling/vit.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_vit.py
  tests/test_zero/test_gemini/test_optim.py
Labels: bug

#4945 [test] merge old components to test to model zoo
  colossalai/testing/__init__.py
  colossalai/testing/utils.py
  tests/components_to_test/__init__.py
  tests/components_to_test/albert.py
  tests/components_to_test/beit.py
  tests/components_to_test/bert.py
  tests/components_to_test/gpt2.py
  tests/components_to_test/hanging_param_model.py
  tests/components_to_test/inline_op_model.py
  tests/components_to_test/registry.py
  tests/components_to_test/repeated_computed_layers.py
  tests/components_to_test/resnet.py
  tests/components_to_test/simple_net.py
  tests/components_to_test/utils/__init__.py
  tests/components_to_test/utils/dummy_data_generator.py
  tests/kit/model_zoo/__init__.py
  tests/kit/model_zoo/custom/__init__.py
  tests/kit/model_zoo/custom/base.py
  tests/kit/model_zoo/custom/hanging_param_model.py
  tests/kit/model_zoo/custom/nested_model.py
  tests/kit/model_zoo/custom/repeated_computed_layers.py
  tests/kit/model_zoo/custom/simple_net.py
  tests/kit/model_zoo/executor.py
  tests/kit/model_zoo/transformers/bert.py
  tests/kit/model_zoo/transformers/blip2.py
  tests/kit/model_zoo/transformers/bloom.py
  tests/kit/model_zoo/transformers/chatglm2.py
  tests/kit/model_zoo/transformers/gpt.py
  tests/kit/model_zoo/transformers/llama.py
  tests/kit/model_zoo/transformers/opt.py
  tests/kit/model_zoo/transformers/sam.py
  tests/kit/model_zoo/transformers/t5.py
  tests/kit/model_zoo/transformers/vit.py
  tests/kit/model_zoo/transformers/whisper.py
  tests/test_legacy/test_amp/test_naive_fp16.py
  tests/test_legacy/test_amp/test_torch_fp16.py
  tests/test_legacy/test_engine/test_engine.py
  tests/test_legacy/test_trainer/test_trainer_with_non_pipe_schedule.py
  tests/test_optimizer/test_nvme.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_gemini_use_rmt.py
  tests/test_zero/test_gemini/test_grad_accum.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_inference.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_runtime_mem_tracer.py
  tests/test_zero/test_gemini/test_search.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
  tests/test_zero/test_gemini/test_zerooptim_state_dict.py
Labels: testing

#4992 [ColossalEval] fix ColossalEval
  applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/dataset_evaluator.py
  applications/ColossalEval/colossal_eval/evaluate/dataset_evaluator/metrics.py
  applications/ColossalEval/colossal_eval/models/huggingface.py
Labels: enhancement, code reviewing

#4996 [doc] add supported feature diagram for hybrid parallel plugin
  docs/source/en/basics/booster_plugins.md
  docs/source/zh-Hans/basics/booster_plugins.md
Labels: documentation
