Repository hpcaitech/ColossalAI, pull requests merged in 2023-09, with the labels that each got.

#4529 [zero]fix zero ckptIO with offload
  colossalai/zero/low_level/low_level_optim.py
  tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
  tests/test_zero/test_low_level/test_zero_ckpt.py
Labels: compatibility

#4589 [pipeline] 1f1b schedule receive microbatch size
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  colossalai/pipeline/schedule/one_f_one_b.py
  tests/test_pipeline/test_schedule/test_oneF_oneB.py
Labels: enhancement

#4591 [checkpointio] optimize zero optim checkpoint io
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/utils.py
  colossalai/zero/low_level/low_level_optim.py
Labels: bug

#4617 [shardformer] adding fine-tuned result of bert to readme.
  colossalai/shardformer/README.md
  examples/language/bert/README.md
Labels: shardformer

#4619 [test] ignore gpt2 shardformer test
  tests/test_shardformer/test_model/test_shard_gpt2.py
Labels: bug

#4618 [zero] hotfix master param sync
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/interface/__init__.py
  colossalai/interface/model.py
  colossalai/zero/low_level/low_level_optim.py
  tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
Labels: bug

#4620 [test] fix gemini checkpoint and gpt test
  tests/test_checkpoint_io/test_plugins_huggingface_compatibility.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
Labels: bug

#4665 [devops] fix concurrency group and compatibility test
  .github/workflows/build_on_pr.yml
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/compatiblity_test_on_schedule.yml
  .github/workflows/doc_check_on_pr.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/example_check_on_pr.yml
Labels: bug, DevOps

#4667 [devops] fix concurrency group
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/example_check_on_pr.yml
Labels: bug, DevOps

#4718 [shardformer] add custom policy in hybrid parallel plugin
  colossalai/booster/plugin/hybrid_parallel_plugin.py
Labels: enhancement, shardformer

#4765 [doc] clean up outdated docs
  docs/sidebars.json
  docs/source/en/advanced_tutorials/add_your_parallel.md
  docs/source/en/advanced_tutorials/define_your_own_parallel_model.md
  docs/source/en/advanced_tutorials/parallelize_your_training_like_Megatron.md
  docs/source/en/basics/colotensor_concept.md
  docs/source/en/basics/configure_parallelization.md
  docs/source/en/basics/define_your_config.md
  docs/source/en/basics/engine_trainer.md
  docs/source/en/basics/initialize_features.md
  docs/source/en/basics/model_checkpoint.md
  docs/source/en/features/1D_tensor_parallel.md
  docs/source/en/features/2D_tensor_parallel.md
  docs/source/en/features/2p5D_tensor_parallel.md
  docs/source/en/features/3D_tensor_parallel.md
  docs/source/en/features/gradient_accumulation.md
  docs/source/en/features/gradient_accumulation_with_booster.md
  docs/source/en/features/gradient_clipping.md
  docs/source/en/features/gradient_clipping_with_booster.md
  docs/source/en/features/gradient_handler.md
  docs/source/en/features/mixed_precision_training.md
  docs/source/en/features/mixed_precision_training_with_booster.md
  docs/source/en/features/zero_with_chunk.md
  docs/source/zh-Hans/advanced_tutorials/add_your_parallel.md
  docs/source/zh-Hans/advanced_tutorials/define_your_own_parallel_model.md
  docs/source/zh-Hans/advanced_tutorials/parallelize_your_training_like_Megatron.md
  docs/source/zh-Hans/basics/colotensor_concept.md
  docs/source/zh-Hans/basics/configure_parallelization.md
  docs/source/zh-Hans/basics/define_your_config.md
  docs/source/zh-Hans/basics/engine_trainer.md
  docs/source/zh-Hans/basics/initialize_features.md
  docs/source/zh-Hans/basics/model_checkpoint.md
  docs/source/zh-Hans/features/1D_tensor_parallel.md
  docs/source/zh-Hans/features/2D_tensor_parallel.md
  docs/source/zh-Hans/features/2p5D_tensor_parallel.md
  docs/source/zh-Hans/features/3D_tensor_parallel.md
  docs/source/zh-Hans/features/gradient_accumulation.md
  docs/source/zh-Hans/features/gradient_accumulation_with_booster.md
  docs/source/zh-Hans/features/gradient_clipping.md
  docs/source/zh-Hans/features/gradient_clipping_with_booster.md
  docs/source/zh-Hans/features/gradient_handler.md
  docs/source/zh-Hans/features/mixed_precision_training.md
  docs/source/zh-Hans/features/mixed_precision_training_with_booster.md
  docs/source/zh-Hans/features/zero_with_chunk.md
Labels: documentation

#4775 [release] update version
  version.txt
Labels: release

#4784 [feature] Colossal-LLaMA-2: Continual Pre-training of LLaMA-2
  applications/Colossal-LLaMA-2/README.md
  applications/Colossal-LLaMA-2/colossal_llama2/__init__.py
  applications/Colossal-LLaMA-2/colossal_llama2/dataset/__init__.py
  applications/Colossal-LLaMA-2/colossal_llama2/dataset/loader.py
  applications/Colossal-LLaMA-2/colossal_llama2/dataset/spliced_and_tokenized_dataset.py
  applications/Colossal-LLaMA-2/colossal_llama2/model/init_model.py
  applications/Colossal-LLaMA-2/colossal_llama2/tokenizer/init_tokenizer.py
  applications/Colossal-LLaMA-2/colossal_llama2/utils/__init__.py
  applications/Colossal-LLaMA-2/colossal_llama2/utils/ckpt_io.py
  applications/Colossal-LLaMA-2/colossal_llama2/utils/flash_attention_patch.py
  applications/Colossal-LLaMA-2/colossal_llama2/utils/froze.py
  applications/Colossal-LLaMA-2/docs/example.md
  applications/Colossal-LLaMA-2/hostfile.example
  applications/Colossal-LLaMA-2/prepare_pretrain_dataset.py
  applications/Colossal-LLaMA-2/requirements.txt
  applications/Colossal-LLaMA-2/train.example.sh
  applications/Colossal-LLaMA-2/train.py
  applications/Colossal-LLaMA-2/version.txt
  applications/README.md
Labels: example, release, chatgpt

#4801 [lazy] support from_pretrained
  .github/workflows/build_on_pr.yml
  .github/workflows/build_on_schedule.yml
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/compatiblity_test_on_schedule.yml
  colossalai/booster/booster.py
  colossalai/interface/pretrained.py
  colossalai/lazy/lazy_init.py
  colossalai/lazy/pretrained.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_lazy/test_from_pretrained.py
Labels: bug, enhancement

#4808 [doc] add lazy init docs
  colossalai/lazy/lazy_init.py
  docs/sidebars.json
  docs/source/en/basics/booster_api.md
  docs/source/en/features/lazy_init.md
  docs/source/zh-Hans/basics/booster_api.md
  docs/source/zh-Hans/features/lazy_init.md
Labels: documentation
