Repository hpcaitech/ColossalAI, pull requests merged in 2023-04, with the labels that each got.

#3411 [test] fixed gemini plugin test
  colossalai/auto_parallel/offload/base_offload_module.py
  colossalai/auto_parallel/offload/mem_optimize.py
  colossalai/auto_parallel/offload/runtime.py
  colossalai/auto_parallel/offload/util.py
  tests/test_auto_parallel/test_offload/test_perf.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_zero/low_level_zero/test_zero1_2.py
Labels: Run Build and Test

#3431 [example] update examples related to zero/gemini
  colossalai/zero/legacy/__init__.py
  examples/language/roberta/configs/colossalai_ddp.py
  examples/language/roberta/configs/colossalai_zero.py
  examples/tutorial/opt/opt/colossalai_zero.py
  examples/tutorial/opt/opt/requirements.txt
  examples/tutorial/opt/opt/run_clm.py
  examples/tutorial/opt/opt/test_ci.sh
  examples/tutorial/opt/test_ci.sh
Labels: Run Build and Test, example, gemini

#3408 [autoparallel]integrate auto parallel feature with new tracer
  colossalai/_analyzer/_subclasses/flop_tensor.py
  colossalai/_analyzer/fx/codegen.py
  colossalai/_analyzer/fx/node_util.py
  colossalai/_analyzer/fx/passes/shape_prop.py
  colossalai/_analyzer/fx/tracer/bias_addition.py
  colossalai/_analyzer/fx/tracer/tracer.py
  colossalai/auto_parallel/meta_profiler/__init__.py
  colossalai/auto_parallel/meta_profiler/meta_registry/activation.py
  colossalai/auto_parallel/meta_profiler/meta_registry/binary_elementwise_ops.py
  colossalai/auto_parallel/meta_profiler/meta_registry/conv.py
  colossalai/auto_parallel/meta_profiler/meta_registry/embedding.py
  colossalai/auto_parallel/meta_profiler/meta_registry/linear.py
  colossalai/auto_parallel/meta_profiler/meta_registry/non_spmd.py
  colossalai/auto_parallel/meta_profiler/meta_registry/norm.py
  colossalai/auto_parallel/meta_profiler/meta_registry/pooling.py
  colossalai/auto_parallel/meta_profiler/meta_registry/tensor.py
  colossalai/auto_parallel/meta_profiler/meta_registry/where.py
  colossalai/auto_parallel/meta_profiler/shard_metainfo.py
  colossalai/auto_parallel/passes/comm_metainfo_pass.py
  colossalai/auto_parallel/passes/meta_info_prop.py
  colossalai/auto_parallel/passes/runtime_apply_pass.py
  colossalai/auto_parallel/passes/runtime_preparation_pass.py
  colossalai/auto_parallel/tensor_shard/initialize.py
  colossalai/auto_parallel/tensor_shard/node_handler/batch_norm_handler.py
  colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py
  colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py
  tests/test_analyzer/__init__.py
  tests/test_auto_parallel/test_pass/test_size_value_converting_pass.py
  tests/test_auto_parallel/test_tensor_shard/test_bias_addition_forward.py
  tests/test_auto_parallel/test_tensor_shard/test_checkpoint.py
  tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_ddp.py
  tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_gemini.py
  tests/test_auto_parallel/test_tensor_shard/test_find_repeat_block.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_runtime_with_gpt_modules.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_solver_with_gpt_module.py
  tests/test_auto_parallel/test_tensor_shard/test_liveness_analysis.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_embedding_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_linear_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_matmul_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_norm_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_tensor_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_where_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/utils.py
  tests/test_auto_parallel/test_tensor_shard/test_param_resharding_cost.py
  tests/test_auto_parallel/test_tensor_shard/test_shape_consistency_pass.py
  tests/test_auto_parallel/test_tensor_shard/test_solver_with_resnet_v2.py
Labels: Run Build and Test, auto-parallel

#3445 [test] reorganize zero/gemini tests
  tests/test_moe/test_moe_checkpoint.py
  tests/test_moe/test_moe_colo_init.py
  tests/test_moe/test_moe_zero_init.py
  tests/test_moe/test_moe_zero_model.py
  tests/test_moe/test_moe_zero_optim.py
  tests/test_zero/test_gemini/test_chunk_mgrv2.py
  tests/test_zero/test_gemini/test_chunkv2.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_gemini_use_rmt.py
  tests/test_zero/test_gemini/test_get_torch_model.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_inference.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_runtime_mem_tracer.py
  tests/test_zero/test_gemini/test_search.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
  tests/test_zero/test_gemini/test_zerooptim_state_dict.py
  tests/test_zero/test_legacy/common.py
  tests/test_zero/test_legacy/test_found_inf.py
  tests/test_zero/test_legacy/test_gemini_manager.py
  tests/test_zero/test_legacy/test_init_context.py
  tests/test_zero/test_legacy/test_param_op.py
  tests/test_zero/test_legacy/test_shard_model_v2.py
  tests/test_zero/test_legacy/test_shard_param.py
  tests/test_zero/test_legacy/test_sharded_optim_state_dict.py
  tests/test_zero/test_legacy/test_sharded_optim_v2.py
  tests/test_zero/test_legacy/test_sharded_optim_with_sync_bn.py
  tests/test_zero/test_legacy/test_state_dict.py
  tests/test_zero/test_legacy/test_tensor_utils.py
  tests/test_zero/test_legacy/test_zero_engine.py
  tests/test_zero/test_low_level/test_grad_acc.py
  tests/test_zero/test_low_level/test_zero1_2.py
  tests/test_zero/test_low_level/test_zero_init.py
  tests/test_zero/test_low_level/test_zero_tp.py
Labels: Run Build and Test, gemini, testing

#3442 [booster] fixed the torch ddp plugin with the new checkpoint api
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  examples/tutorial/new_api/torch_ddp/README.md
Labels: Run Build and Test

#3461 [checkpoint] support huggingface style sharded checkpoint
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/index_file.py
  colossalai/checkpoint_io/utils.py
  tests/test_checkpoint_io/test_general_checkpoint_io.py
Labels: Run Build and Test

#3520 [chat] add zero2 cpu strategy for sft training
  applications/Chat/examples/train_sft.py
Labels: chatgpt

#3479 [checkpoint] Shard saved checkpoint need to be compatible with the naming format of hf checkpoint files
  colossalai/checkpoint_io/checkpoint_io_base.py
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/utils.py
Labels: Run Build and Test

#3553 [lazyinit] fix clone and deepcopy
  colossalai/utils/model/experimental.py
Labels: Run Build and Test, lazyinit

#3552 [misc] add verbose arg for zero and op builder
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/zero/gemini/chunk/utils.py
  colossalai/zero/gemini/gemini_ddp.py
  colossalai/zero/gemini/gemini_optimizer.py
  colossalai/zero/low_level/low_level_optim.py
  colossalai/zero/wrapper.py
  op_builder/builder.py
  op_builder/utils.py
Labels: Run Build and Test, API

#3581 [gemini] support save state dict in shards
  colossalai/zero/gemini/gemini_ddp.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
Labels: Run Build and Test, gemini

#3589 [fx] fix meta tensor registration
  colossalai/_analyzer/_subclasses/_meta_registration.py
Labels: bug, Run Build and Test

#3590 [gemini] state dict supports fp16
  colossalai/zero/gemini/gemini_ddp.py
Labels: Run Build and Test, gemini

#3608 [Chat] Add evaluate feature for Chat application
  applications/Chat/README.md
  applications/Chat/evaluate/README.md
  applications/Chat/evaluate/evaluate.py
  applications/Chat/evaluate/evaluate.sh
  applications/Chat/evaluate/format_questions.py
  applications/Chat/evaluate/format_questions.sh
  applications/Chat/evaluate/generate_answers.py
  applications/Chat/evaluate/generate_answers.sh
  applications/Chat/evaluate/generate_gpt35_answers.py
  applications/Chat/evaluate/generate_gpt35_answers.sh
  applications/Chat/evaluate/merge.py
  applications/Chat/evaluate/utils.py
Labels: chatgpt

#3628 [devops] fix chat ci
  .github/workflows/run_chatgpt_examples.yml
  .github/workflows/run_chatgpt_unit_tests.yml
Labels: bug, DevOps, chatgpt

#3594 [booster] add low level zero plugin
  colossalai/booster/plugin/__init__.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/zero/low_level/low_level_optim.py
  tests/kit/model_zoo/diffusers/diffusers.py
  tests/kit/model_zoo/torchaudio/torchaudio.py
  tests/kit/model_zoo/torchvision/torchvision.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_booster/test_plugin/test_low_level_zero_plugin.py
  tests/test_booster/test_plugin/test_torch_ddp_plugin.py
Labels: Run Build and Test, API

#3641 [gemini] accelerate inference
  .github/workflows/run_chatgpt_unit_tests.yml
  applications/Chat/benchmarks/benchmark_opt_lora_dummy.py
  applications/Chat/coati/dataset/prompt_dataset.py
  applications/Chat/coati/models/generation.py
  applications/Chat/coati/models/generation_utils.py
  applications/Chat/coati/trainer/ppo.py
  applications/Chat/coati/trainer/strategies/colossalai.py
  applications/Chat/tests/test_checkpoint.py
  colossalai/zero/gemini/gemini_ddp.py
  tests/components_to_test/__init__.py
  tests/components_to_test/utils/__init__.py
  tests/components_to_test/utils/executor.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
Labels: Run Build and Test, gemini, chatgpt

#3647 [chat] polish performance evaluator
  applications/Chat/coati/trainer/callbacks/performance_evaluator.py
Labels: chatgpt

#3648 [chat] refactor trainer
  applications/Chat/benchmarks/README.md
  applications/Chat/benchmarks/benchmark_gpt_dummy.py
  applications/Chat/benchmarks/benchmark_gpt_dummy.sh
  applications/Chat/benchmarks/benchmark_opt_lora_dummy.py
  applications/Chat/coati/trainer/base.py
  applications/Chat/coati/trainer/ppo.py
  applications/Chat/coati/trainer/sft.py
  applications/Chat/coati/trainer/utils.py
  applications/Chat/examples/train_dummy.py
  applications/Chat/examples/train_dummy.sh
  applications/Chat/examples/train_prompts.py
  applications/Chat/examples/train_sft.py
Labels: chatgpt

#3646 [Doc] enhancement on README.md for chat examples
  applications/Chat/examples/README.md
  applications/Chat/examples/test_ci.sh
  applications/Chat/examples/train_prompts.py
  applications/Chat/examples/train_prompts.sh
Labels: chatgpt

#3653 [chat] remove lm model class
  applications/Chat/coati/models/__init__.py
  applications/Chat/coati/models/base/__init__.py
  applications/Chat/coati/models/base/lm.py
  applications/Chat/coati/models/bloom/__init__.py
  applications/Chat/coati/models/bloom/bloom_lm.py
  applications/Chat/coati/models/gpt/__init__.py
  applications/Chat/coati/models/gpt/gpt_lm.py
  applications/Chat/coati/models/llama/__init__.py
  applications/Chat/coati/models/llama/llama_lm.py
  applications/Chat/coati/models/lora.py
  applications/Chat/coati/models/opt/__init__.py
  applications/Chat/coati/models/opt/opt_lm.py
  applications/Chat/coati/trainer/sft.py
  applications/Chat/coati/trainer/strategies/base.py
  applications/Chat/coati/trainer/strategies/colossalai.py
  applications/Chat/coati/trainer/strategies/ddp.py
  applications/Chat/coati/trainer/strategies/naive.py
  applications/Chat/coati/utils/tokenizer_utils.py
  applications/Chat/examples/test_ci.sh
  applications/Chat/examples/train_sft.py
Labels: chatgpt

#3654 [chat] refactor model save/load logic
  applications/Chat/README.md
  applications/Chat/coati/models/base/__init__.py
  applications/Chat/coati/trainer/ppo.py
  applications/Chat/coati/trainer/rm.py
  applications/Chat/coati/trainer/sft.py
  applications/Chat/coati/trainer/strategies/base.py
  applications/Chat/coati/trainer/strategies/colossalai.py
  applications/Chat/coati/trainer/strategies/ddp.py
  applications/Chat/coati/trainer/strategies/naive.py
  applications/Chat/examples/README.md
  applications/Chat/examples/train_prompts.py
  applications/Chat/examples/train_reward_model.py
  applications/Chat/examples/train_sft.py
  applications/Chat/tests/test_checkpoint.py
Labels: chatgpt

#3173 [zero] Suggests a minor change to confusing variable names in the ZeRO optimizer.
  colossalai/zero/low_level/_utils.py
  colossalai/zero/low_level/bookkeeping/parameter_store.py
  colossalai/zero/low_level/low_level_optim.py
Labels: Run Build and Test
