Repository hpcaitech/ColossalAI, pull requests merged in 2023-06, with the labels that each got.

#3872 [bf16] add bf16 support for gemini
  colossalai/zero/gemini/gemini_ddp.py
  colossalai/zero/gemini/gemini_optimizer.py
  tests/test_zero/test_gemini/test_optim.py
Labels: enhancement

#3877 [bf16] add bf16 support for plugins
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
Labels: enhancement

#3891 [lazy] refactor lazy init
  colossalai/lazy/__init__.py
  colossalai/lazy/lazy_init.py
  colossalai/utils/model/lazy_init_context.py
  colossalai/zero/gemini/gemini_ddp.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_lazy/lazy_init_utils.py
  tests/test_lazy/test_distribute.py
  tests/test_lazy/test_models.py
  tests/test_utils/test_lazy_init_ctx.py
Labels: enhancement

#3890 [doc]update moe chinese document.
  docs/source/en/advanced_tutorials/integrate_mixture_of_experts_into_your_model.md
  docs/source/en/concepts/colossalai_overview.md
  docs/source/zh-Hans/advanced_tutorials/integrate_mixture_of_experts_into_your_model.md
  docs/source/zh-Hans/concepts/colossalai_overview.md
Labels: documentation, API

#3882 [bf16] add bf16 support
  colossalai/amp/naive_amp/mixed_precision_mixin/__init__.py
  colossalai/amp/naive_amp/mixed_precision_mixin/base.py
  colossalai/amp/naive_amp/mixed_precision_mixin/bf16.py
  colossalai/amp/naive_amp/mixed_precision_mixin/fp16.py
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/kernel/cuda_native/csrc/type_shim.h
  colossalai/nn/optimizer/cpu_adam.py
  colossalai/nn/optimizer/fused_adam.py
  colossalai/nn/optimizer/hybrid_adam.py
  colossalai/zero/gemini/gemini_ddp.py
  colossalai/zero/gemini/gemini_optimizer.py
  colossalai/zero/legacy/init_ctx/init_context.py
  colossalai/zero/legacy/sharded_model/_utils.py
  colossalai/zero/legacy/sharded_model/sharded_model_v2.py
  colossalai/zero/legacy/sharded_optim/sharded_optim_v2.py
  colossalai/zero/low_level/low_level_optim.py
  tests/test_optimizer/test_adam_kernel.py
  tests/test_optimizer/test_adam_optim.py
  tests/test_optimizer/test_cpu_adam.py
  tests/test_optimizer/test_fused_adam.py
  tests/test_optimizer/test_fused_adam_kernel.py
  tests/test_optimizer/test_hybrid_adam.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_legacy/test_zero_engine.py
  tests/test_zero/test_low_level/test_grad_acc.py
  tests/test_zero/test_low_level/test_zero1_2.py
Labels: enhancement

#3880 [evaluate] support evaluation for english
  applications/Chat/evaluate/README.md
  applications/Chat/evaluate/config/config_en.json
  applications/Chat/evaluate/eval.py
  applications/Chat/evaluate/evaluator.py
  applications/Chat/evaluate/gpt_evaluate.py
  applications/Chat/evaluate/metrics.py
  applications/Chat/evaluate/prompt/battle_prompt/battle_prompt_en.json
  applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_en.json
  applications/Chat/evaluate/requirements.txt
  applications/Chat/evaluate/utils.py
Labels: code reviewing

#3902 [devops] improving testmon cache
  .github/workflows/README.md
  .github/workflows/build_on_pr.yml
Labels: DevOps

#3898 [doc] Fix a bug about booster api in the documentation.
  colossalai/booster/booster.py
  docs/source/en/features/zero_with_chunk.md
  docs/source/zh-Hans/features/zero_with_chunk.md
Labels: documentation

#3910 [devops] hotfix CI about testmon cache
  .github/workflows/build_on_pr.yml
Labels: bug, DevOps

#3911 [lazy] fix compatibility problem on torch 1.13
  colossalai/lazy/lazy_init.py
Labels: bug

#3917 [devops] hotfix testmon cache clean logic
  .github/workflows/build_on_pr.yml
Labels: bug

#3920 [workflow] added docker latest tag for release
  .github/workflows/release_docker_after_publish.yml
Labels: DevOps

#3913 [example] Modify palm example with the new booster API
  examples/language/palm/README.md
  examples/language/palm/run.sh
  examples/language/palm/test_ci.sh
  examples/language/palm/train.py
Labels: example

#3922 [doc] add lazy init tutorial
  docs/sidebars.json
  docs/source/en/features/lazy_init.md
  docs/source/zh-Hans/features/lazy_init.md
Labels: documentation

#3919 [devops] update torch version in compability test
  .compatibility
Labels: DevOps

#3845 [dtensor] updated api and doc
  colossalai/device/README.md
  colossalai/device/device_mesh.py
  colossalai/lazy/lazy_init.py
  colossalai/tensor/comm_spec.py
  colossalai/tensor/d_tensor/RAEDME.md
  colossalai/tensor/d_tensor/__init__.py
  colossalai/tensor/d_tensor/comm_spec.py
  colossalai/tensor/d_tensor/d_tensor.py
  colossalai/tensor/d_tensor/layout.py
  colossalai/tensor/d_tensor/layout_converter.py
  tests/test_device/test_device_mesh.py
  tests/test_device/test_init_logical_pg.py
  tests/test_lazy/lazy_init_utils.py
  tests/test_lazy/test_distribute.py
  tests/test_tensor/test_dtensor/test_comm_spec.py
  tests/test_tensor/test_dtensor/test_dtensor.py
  tests/test_tensor/test_dtensor/test_layout_converter.py
  tests/test_tensor/test_shape_consistency.py
  tests/test_tensor/test_sharded_linear.py
  tests/test_tensor/test_sharding_spec.py
Labels: enhancement, API

#3926 [feature] updated device mesh and dtensor
  colossalai/device/README.md
  colossalai/device/device_mesh.py
  colossalai/lazy/lazy_init.py
  colossalai/tensor/comm_spec.py
  colossalai/tensor/d_tensor/RAEDME.md
  colossalai/tensor/d_tensor/__init__.py
  colossalai/tensor/d_tensor/comm_spec.py
  colossalai/tensor/d_tensor/d_tensor.py
  colossalai/tensor/d_tensor/layout.py
  colossalai/tensor/d_tensor/layout_converter.py
  colossalai/tensor/d_tensor/sharding_spec.py
  tests/test_device/test_device_mesh.py
  tests/test_device/test_init_logical_pg.py
  tests/test_lazy/lazy_init_utils.py
  tests/test_lazy/test_distribute.py
  tests/test_tensor/test_dtensor/test_comm_spec.py
  tests/test_tensor/test_dtensor/test_dtensor.py
  tests/test_tensor/test_dtensor/test_layout_converter.py
  tests/test_tensor/test_shape_consistency.py
  tests/test_tensor/test_sharded_linear.py
  tests/test_tensor/test_sharding_spec.py
Labels: enhancement, API

#3924 [evaluation] support UniEval and add CHRF metric
  applications/Chat/evaluate/README.md
  applications/Chat/evaluate/config/config_cn.json
  applications/Chat/evaluate/config/config_en.json
  applications/Chat/evaluate/eval.py
  applications/Chat/evaluate/evaluator.py
  applications/Chat/evaluate/gpt_evaluate.py
  applications/Chat/evaluate/metrics.py
  applications/Chat/evaluate/unieval/__init__.py
  applications/Chat/evaluate/unieval/evaluator.py
  applications/Chat/evaluate/unieval/scorer.py
  applications/Chat/evaluate/unieval/utils.py
  applications/Chat/evaluate/utils.py
Labels: code reviewing

#3905 [example] Adding an example of training dreambooth with the new booster API
  examples/images/dreambooth/README.md
  examples/images/dreambooth/colossalai.sh
  examples/images/dreambooth/dreambooth.sh
  examples/images/dreambooth/test_ci.sh
  examples/images/dreambooth/train_dreambooth_colossalai.py
  examples/images/dreambooth/train_dreambooth_colossalai_lora.py
Labels: example

#3934 [gemini] fixed the gemini checkpoint io
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/checkpoint_io/index_file.py
  colossalai/zero/gemini/gemini_ddp.py
Labels: bug, gemini

#3907 [shardformer] Align bert value
  colossalai/shardformer/README.md
  colossalai/shardformer/__init__.py
  colossalai/shardformer/layer/dist_crossentropy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  colossalai/shardformer/test/config.py
  colossalai/shardformer/test/module_test.py
  colossalai/shardformer/test/test.py
  tests/test_shardformer/test_model/test_shard_bert.py
  tests/test_shardformer/test_module/test_distcrossentropy.py
Labels: shardformer

#3944 [elixir] updated readme
  colossalai/elixir/README.md
  colossalai/elixir/__init__.py
Labels: documentation

#3939 [elixir] moved simulator build to op_builder
  colossalai/elixir/search/simulator.py
  op_builder/__init__.py
  op_builder/elixir_simulator.py
  setup.py
  tests/test_elixir/test_src/test_move.py
Labels: enhancement

#3960 [workflow] cancel duplicated workflow jobs
  .github/workflows/build_on_pr.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/doc_check_on_pr.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/example_check_on_pr.yml
Labels: enhancement, DevOps

#3928 [shardformer] Unit test
  colossalai/shardformer/layer/dropout.py
  colossalai/shardformer/shard/slicer.py
  tests/test_shardformer/test_module/test_dropout.py
  tests/test_shardformer/test_module/test_slicer.py
Labels: shardformer

#3980 [workflow] fixed the directory check in build
  .github/workflows/build_on_pr.yml
Labels: bug, DevOps

#3972 [evaluate] Support gpt evaluation with reference
  applications/Chat/evaluate/README.md
  applications/Chat/evaluate/config/config_cn.json
  applications/Chat/evaluate/config/config_en.json
  applications/Chat/evaluate/eval.py
  applications/Chat/evaluate/evaluator.py
  applications/Chat/evaluate/gpt_evaluate.py
  applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_cn.json
  applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_en.json
Labels: chatgpt, code reviewing

#3990 [device] support init device mesh from process group
  colossalai/device/device_mesh.py
  tests/test_device/test_device_mesh.py
Labels: API

#3984 [checkpointio] General Checkpointing of Sharded Optimizers
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  colossalai/booster/plugin/torch_fsdp_plugin.py
  colossalai/checkpoint_io/checkpoint_io_base.py
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/index_file.py
  colossalai/checkpoint_io/utils.py
  tests/test_checkpoint_io/test_general_checkpoint_io.py
Labels: API, testing

#3993 [booster] make optimizer argument optional for boost
  colossalai/booster/booster.py
  colossalai/booster/mixed_precision/fp16_torch.py
  colossalai/booster/mixed_precision/mixed_precision_base.py
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/booster/plugin/plugin_base.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  colossalai/booster/plugin/torch_fsdp_plugin.py
  tests/test_autochunk/test_autochunk_diffuser/test_autochunk_unet.py
Labels: API

#3979 [Shardformer] Downstream bert
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  tests/test_shardformer/test_model/test_shard_bert.py
Labels: shardformer

#3996 [shardformer] integrated linear 1D with dtensor
  colossalai/nn/layer/base_layer.py
  colossalai/shardformer/layer/_operation.py
  colossalai/shardformer/layer/dropout.py
  colossalai/shardformer/layer/layers.py
  colossalai/shardformer/layer/utils.py
  colossalai/tensor/d_tensor/api.py
  colossalai/tensor/d_tensor/layout.py
  colossalai/tensor/d_tensor/layout_converter.py
  tests/test_shardformer/test_layer/test_linear_1d.py
Labels: shardformer

#4011 [shardformer] integrate with dist layer
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/shard/sharder.py
  tests/test_shardformer/test_model/test_shard_bert.py
Labels: shardformer

#4002 [checkpointio] sharded optimizers checkpointing feature adapted for DDP plugin
  colossalai/booster/booster.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  colossalai/checkpoint_io/checkpoint_io_base.py
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/utils.py
  tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
Labels: API

#4018 [shardformer] removed inplace tensor sharding
  colossalai/shardformer/layer/layers.py
  colossalai/tensor/d_tensor/api.py
Labels: enhancement, shardformer

#4016 [shardformer] updated doc
  colossalai/shardformer/README.md
Labels: documentation, shardformer

#4021 Refactor/shardformer
  colossalai/device/device_mesh.py
  colossalai/nn/layer/base_layer.py
  colossalai/shardformer/README.md
  colossalai/shardformer/__init__.py
  colossalai/shardformer/layer/_operation.py
  colossalai/shardformer/layer/dist_crossentropy.py
  colossalai/shardformer/layer/dropout.py
  colossalai/shardformer/layer/layers.py
  colossalai/shardformer/layer/utils.py
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/basepolicy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/shard/__init__.py
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  colossalai/shardformer/shard/shardformer.py
  colossalai/shardformer/shard/slicer.py
  colossalai/shardformer/utils/__init__.py
  colossalai/tensor/d_tensor/RAEDME.md
  colossalai/tensor/d_tensor/api.py
  colossalai/tensor/d_tensor/layout.py
  colossalai/tensor/d_tensor/layout_converter.py
  tests/test_device/test_device_mesh.py
  tests/test_shardformer/test_layer/test_dropout.py
  tests/test_shardformer/test_layer/test_embedding.py
  tests/test_shardformer/test_layer/test_linear_1d.py
  tests/test_shardformer/test_layer/test_vocab_parallel_embedding_1d.py
  tests/test_shardformer/test_model/test_shard_bert.py
Labels: shardformer

#4026 [test] fixed codefactor format report
  tests/test_checkpoint_io/test_general_checkpoint_io.py
Labels: testing

#4024 [shardformer] fix bert and gpt downstream with new api
  colossalai/shardformer/policies/basepolicy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  colossalai/shardformer/shard/shardformer.py
  tests/test_shardformer/test_model/test_shard_bert.py
Labels: testing, shardformer

#4028 [example] fix bucket size in example of gpt gemini
  examples/language/gpt/gemini/train_gpt_demo.py
Labels: example

#4043 [devops] fix build on pr ci
  .github/workflows/build_on_pr.yml
Labels: bug, DevOps

#4045 [shardformer] supported T5 and its variants
  colossalai/shardformer/README.md
  colossalai/shardformer/layer/layers.py
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/basepolicy.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/shard/sharder.py
  colossalai/testing/__init__.py
  colossalai/testing/comparison.py
  tests/test_shardformer/test_model/test_shard_llama.py
  tests/test_shardformer/test_model/test_shard_t5.py
Labels: enhancement, shardformer

#4039 [cluster] add process group mesh
  colossalai/cluster/__init__.py
  colossalai/cluster/process_group_mesh.py
  tests/test_cluster/test_process_group_mesh.py
Labels: enhancement

#4049 [shardformer] adapted T5 and LLaMa test to use kit
  colossalai/shardformer/layer/embedding1d.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/shard/sharder.py
  colossalai/testing/comparison.py
  tests/kit/model_zoo/registry.py
  tests/kit/model_zoo/transformers/__init__.py
  tests/kit/model_zoo/transformers/llama.py
  tests/kit/model_zoo/transformers/t5.py
  tests/test_booster/test_mixed_precision/test_fp16_torch.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_booster/test_plugin/test_low_level_zero_plugin.py
  tests/test_booster/test_plugin/test_torch_ddp_plugin.py
  tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
  tests/test_fx/test_tracer/test_hf_model/test_hf_diffuser.py
  tests/test_fx/test_tracer/test_timm_model/test_timm_model.py
  tests/test_fx/test_tracer/test_torchaudio_model/test_torchaudio_model.py
  tests/test_lazy/lazy_init_utils.py
  tests/test_lazy/test_distribute.py
  tests/test_shardformer/__init__.py
  tests/test_shardformer/test_model/__init__.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_llama.py
  tests/test_shardformer/test_model/test_shard_t5.py
Labels: testing, shardformer

#4062 [shardformer] support module saving and loading
  colossalai/checkpoint_io/utils.py
  colossalai/device/device_mesh.py
  colossalai/lazy/lazy_init.py
  colossalai/shardformer/layer/embedding.py
  colossalai/shardformer/layer/linear.py
  colossalai/shardformer/layer/linear_conv.py
  colossalai/shardformer/layer/parallel_module.py
  colossalai/tensor/d_tensor/__init__.py
  colossalai/tensor/d_tensor/api.py
  colossalai/tensor/d_tensor/d_tensor.py
  colossalai/tensor/d_tensor/layout.py
  colossalai/tensor/d_tensor/layout_converter.py
  colossalai/tensor/d_tensor/utils.py
  test.py
  tests/test_lazy/lazy_init_utils.py
  tests/test_shardformer/test_layer/test_embedding.py
  tests/test_shardformer/test_layer/test_linear_1d.py
  tests/test_shardformer/test_layer/test_vocab_parallel_embedding_1d.py
  tests/test_tensor/test_dtensor/test_comm_spec.py
  tests/test_tensor/test_dtensor/test_dtensor.py
  tests/test_tensor/test_dtensor/test_layout_converter.py
Labels: shardformer

#4067 [shardformer] add linearconv1d test
  colossalai/shardformer/layer/linear_conv.py
  colossalai/shardformer/policies/gpt2.py
  tests/test_shardformer/test_layer/test_linearconv_1d.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
Labels: testing, shardformer

#4073 [shardformer] supported fused qkv checkpoint
  colossalai/shardformer/layer/_operation.py
  colossalai/shardformer/layer/embedding.py
  colossalai/shardformer/layer/linear.py
  colossalai/shardformer/layer/linear_conv.py
  colossalai/shardformer/layer/parallel_module.py
  colossalai/tensor/d_tensor/__init__.py
  colossalai/tensor/d_tensor/api.py
  tests/test_shardformer/test_layer/test_linear_1d.py
  tests/test_shardformer/test_layer/test_linearconv_1d.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
Labels: enhancement, shardformer

#4056 [gemini] Fix a bug in chunk configuration searching
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/zero/gemini/chunk/search_utils.py
  colossalai/zero/gemini/chunk/utils.py
  colossalai/zero/gemini/gemini_ddp.py
  tests/test_auto_parallel/test_offload/test_perf.py
  tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_gemini.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_tensor/test_tp_with_zero.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_gemini_use_rmt.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_inference.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_search.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
  tests/test_zero/test_gemini/test_zerooptim_state_dict.py
Labels: bug

#4093 [pipeline] add stage manager
  colossalai/pipeline/stage_manager.py
  tests/test_pipeline/test_stage_manager.py
Labels: enhancement

#4090 [examples] copy resnet example to image
  examples/images/resnet/.gitignore
  examples/images/resnet/README.md
  examples/images/resnet/eval.py
  examples/images/resnet/requirements.txt
  examples/images/resnet/test_ci.sh
  examples/images/resnet/train.py
Labels: example

#4091 [shardformer] shardformer support opt models
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/opt.py
  tests/kit/model_zoo/transformers/opt.py
  tests/test_fx/test_tracer/test_hf_model/test_hf_opt.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_opt.py
Labels: testing, shardformer

#4106 [workflow] added status check for test coverage workflow
  .github/workflows/report_test_coverage.yml
Labels: DevOps

#4100 [pipeline] implement p2p communication
  colossalai/pipeline/p2p.py
  tests/test_pipeline/test_p2p_communication.py
  tests/test_pipeline/test_stage_manager.py
Labels: enhancement

#4080 [chat] refactor trainer class
  applications/Chat/README.md
  applications/Chat/benchmarks/benchmark_opt_lora_dummy.py
  applications/Chat/coati/trainer/__init__.py
  applications/Chat/coati/trainer/base.py
  applications/Chat/coati/trainer/ppo.py
  applications/Chat/coati/trainer/rm.py
  applications/Chat/coati/trainer/sft.py
  applications/Chat/coati/trainer/strategies/colossalai.py
  applications/Chat/coati/trainer/utils.py
  applications/Chat/examples/README.md
  applications/Chat/examples/community/peft/train_peft_prompts.py
  applications/Chat/examples/test_ci.sh
  applications/Chat/examples/train_prompts.py
  applications/Chat/examples/train_prompts.sh
  applications/Chat/examples/train_reward_model.py
  applications/Chat/examples/train_sft.py
Labels: chatgpt

#4115 [pipeline] refactor 1f1b schedule
  colossalai/interface/optimizer.py
  colossalai/pipeline/schedule/__init__.py
  colossalai/pipeline/schedule/_utils.py
  colossalai/pipeline/schedule/base.py
  colossalai/pipeline/schedule/one_f_one_b.py
  tests/test_pipeline/test_schedule/test_pipeline_schedule_utils.py
Labels: enhancement

#4094 [chat] remove naive strategy and split colossalai strategy
  applications/Chat/README.md
  applications/Chat/benchmarks/benchmark_opt_lora_dummy.py
  applications/Chat/benchmarks/ray/1mmt_dummy.py
  applications/Chat/benchmarks/ray/mmmt_dummy.py
  applications/Chat/coati/ray/detached_trainer_ppo.py
  applications/Chat/coati/ray/utils.py
  applications/Chat/coati/trainer/callbacks/save_checkpoint.py
  applications/Chat/coati/trainer/ppo.py
  applications/Chat/coati/trainer/sft.py
  applications/Chat/coati/trainer/strategies/__init__.py
  applications/Chat/coati/trainer/strategies/colossalai.py
  applications/Chat/coati/trainer/strategies/ddp.py
  applications/Chat/coati/trainer/strategies/naive.py
  applications/Chat/examples/README.md
  applications/Chat/examples/community/peft/train_peft_prompts.py
  applications/Chat/examples/community/peft/train_peft_sft.py
  applications/Chat/examples/community/ray/train_prompts_on_ray.py
  applications/Chat/examples/ray/1mmt_prompt.py
  applications/Chat/examples/ray/mmmt_prompt.py
  applications/Chat/examples/test_ci.sh
  applications/Chat/examples/train_prompts.py
  applications/Chat/examples/train_reward_model.py
  applications/Chat/examples/train_sft.py
  applications/Chat/tests/test_checkpoint.py
  applications/Chat/tests/test_data.py
Labels: chatgpt

#4103 [shardformer] integrate with data parallelism
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  colossalai/shardformer/shard/shardformer.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_bert.py
  tests/test_shardformer/test_model/test_shard_bloom.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
  tests/test_shardformer/test_model/test_shard_llama.py
  tests/test_shardformer/test_model/test_shard_opt.py
  tests/test_shardformer/test_model/test_shard_t5.py
  tests/test_shardformer/test_with_torch_ddp.py
Labels: enhancement, shardformer

#4101 [shardformer] import huggingface implicitly
  colossalai/shardformer/policies/autopolicy.py
  colossalai/shardformer/policies/basepolicy.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/llama.py
  colossalai/shardformer/policies/opt.py
  colossalai/shardformer/policies/t5.py
  colossalai/shardformer/policies/vit.py
  colossalai/shardformer/shard/shard_config.py
Labels: enhancement, shardformer

#4126 [shardformer] write an shardformer example with bert finetuning
  colossalai/shardformer/README.md
  colossalai/shardformer/examples/data.py
  colossalai/shardformer/examples/shardformer_benchmark.py
  colossalai/shardformer/examples/shardformer_benchmark.sh
  colossalai/shardformer/shard/shard_config.py
Labels: example
