Repository hpcaitech/ColossalAI, pull requests merged in 2023-08, with the labels that each got.

#4332 [release] update version
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/compatiblity_test_on_schedule.yml
  .github/workflows/cuda_ext_check_before_merge.yml
  pytest.ini
  version.txt
Labels: release

#4359 [test] remove useless tests
  colossalai/utils/checkpoint_io/__init__.py
  colossalai/utils/checkpoint_io/backend.py
  colossalai/utils/checkpoint_io/constant.py
  colossalai/utils/checkpoint_io/convertor.py
  colossalai/utils/checkpoint_io/distributed.py
  colossalai/utils/checkpoint_io/io.py
  colossalai/utils/checkpoint_io/meta.py
  colossalai/utils/checkpoint_io/reader.py
  colossalai/utils/checkpoint_io/utils.py
  colossalai/utils/checkpoint_io/writer.py
  tests/test_lazy/test_distribute.py
  tests/test_utils/test_checkpoint_io/test_build_checkpoints.py
  tests/test_utils/test_checkpoint_io/test_load.py
  tests/test_utils/test_checkpoint_io/test_merge.py
  tests/test_utils/test_checkpoint_io/test_merge_param.py
  tests/test_utils/test_checkpoint_io/test_redist.py
  tests/test_utils/test_checkpoint_io/test_save.py
  tests/test_utils/test_checkpoint_io/test_unmerge_param.py
  tests/test_zero/test_legacy/common.py
  tests/test_zero/test_legacy/test_found_inf.py
  tests/test_zero/test_legacy/test_gemini_manager.py
  tests/test_zero/test_legacy/test_init_context.py
  tests/test_zero/test_legacy/test_param_op.py
  tests/test_zero/test_legacy/test_shard_model_v2.py
  tests/test_zero/test_legacy/test_shard_param.py
  tests/test_zero/test_legacy/test_sharded_optim_state_dict.py
  tests/test_zero/test_legacy/test_sharded_optim_v2.py
  tests/test_zero/test_legacy/test_sharded_optim_with_sync_bn.py
  tests/test_zero/test_legacy/test_state_dict.py
  tests/test_zero/test_legacy/test_tensor_utils.py
  tests/test_zero/test_legacy/test_zero_engine.py
Labels: testing

#4384 [shardformer/sequence parallel] Support sequence parallel for gpt2
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  colossalai/kernel/cuda_native/flash_attention.py
  colossalai/kernel/cuda_native/scaled_softmax.py
  colossalai/shardformer/layer/_operation.py
  colossalai/shardformer/layer/linear.py
  colossalai/shardformer/layer/qkv_fused_linear.py
  colossalai/shardformer/modeling/gpt2_seq.py
  colossalai/shardformer/policies/base_policy.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/shard/shard_config.py
  requirements/requirements-test.txt
  tests/kit/model_zoo/transformers/gpt.py
  tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
  tests/test_shardformer/test_layer/test_linear_1d.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
  tests/test_utils/test_flash_attention.py
Labels: shardformer, sequence parallel

#4379 [gemini] remove distributed-related part from colotensor
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/tensor/colo_parameter.py
  colossalai/tensor/colo_tensor.py
  colossalai/tensor/param_op_hook.py
  colossalai/zero/gemini/chunk/chunk.py
  colossalai/zero/gemini/chunk/manager.py
  colossalai/zero/gemini/chunk/search_utils.py
  colossalai/zero/gemini/gemini_ddp.py
  pytest.ini
  requirements/requirements-test.txt
  tests/kit/model_zoo/transformers/albert.py
  tests/kit/model_zoo/transformers/bert.py
  tests/kit/model_zoo/transformers/gpt.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_data_pipeline_tensor_parallel/test_cifar_with_data_pipeline_tensor_v2.py
  tests/test_ddp/test_ddp_ignore_params.py
  tests/test_ddp/test_ddp_state_dict.py
  tests/test_ddp/test_reducer.py
  tests/test_ops/test_addmm_tp.py
  tests/test_ops/test_embedding_bag_tp.py
  tests/test_ops/test_embedding_tp.py
  tests/test_ops/test_linear_tp.py
  tests/test_ops/test_loss_func.py
  tests/test_ops/test_op.py
  tests/test_ops/test_view.py
  tests/test_pipeline/test_pipelinable.py
  tests/test_tensor/core/test_tensor.py
  tests/test_tensor/model/test_gpt2.py
  tests/test_tensor/model/test_model.py
  tests/test_tensor/model/test_module_spec.py
  tests/test_tensor/test_colo_checkpoint_tools.py
  tests/test_tensor/test_context.py
  tests/test_tensor/test_sharded_linear.py
  tests/test_tensor/test_tp_with_zero.py
  tests/test_utils/test_colo_checkpoint.py
  tests/test_utils/test_flash_attention.py
  tests/test_utils/test_norm_gradient_clipping.py
  tests/test_zero/test_gemini/test_chunk_mgrv2.py
  tests/test_zero/test_gemini/test_chunkv2.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_gemini_use_rmt.py
  tests/test_zero/test_gemini/test_get_torch_model.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_inference.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_runtime_mem_tracer.py
  tests/test_zero/test_gemini/test_search.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
  tests/test_zero/test_gemini/test_zerooptim_state_dict.py
  tests/test_zero/test_low_level/test_zero_init.py
  tests/test_zero/test_low_level/test_zero_tp.py
Labels: enhancement

#4404 [hotfix] fix unsafe calculation in zero
  colossalai/zero/low_level/bookkeeping/bucket_store.py
  colossalai/zero/low_level/low_level_optim.py
  tests/test_zero/test_low_level/test_zero1_2.py
Labels: bug

#4398 [gemini] refactor gemini optimizer and gemini ddp
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/zero/__init__.py
  colossalai/zero/gemini/__init__.py
  colossalai/zero/gemini/gemini_ddp.py
  colossalai/zero/gemini/gemini_optimizer.py
  colossalai/zero/gemini/memory_tracer/memory_stats.py
  colossalai/zero/gemini/utils.py
  colossalai/zero/wrapper.py
  examples/community/roberta/pretraining/run_pretraining.py
  examples/language/palm/train.py
  examples/tutorial/opt/opt/requirements.txt
  examples/tutorial/opt/opt/run_clm.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_checkpoint_io/test_gemini_torch_compability.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_gemini_use_rmt.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_inference.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
  tests/test_zero/test_gemini/test_zerooptim_state_dict.py
Labels: enhancement

#4443 [gemini] add static placement policy
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/zero/gemini/gemini_ddp.py
  colossalai/zero/gemini/gemini_mgr.py
  colossalai/zero/gemini/placement_policy.py
  requirements/requirements-test.txt
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_zero/test_gemini/test_fwd_bwd.py
  tests/test_zero/test_gemini/test_grad_clip.py
  tests/test_zero/test_gemini/test_inference.py
  tests/test_zero/test_gemini/test_optim.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
  tests/test_zero/test_gemini/test_zerooptim_state_dict.py
Labels: enhancement

#4452 [devops] add large-scale distributed test marker
  .github/workflows/build_on_pr.yml
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/compatiblity_test_on_schedule.yml
  applications/Chat/tests/test_dataset.py
  applications/Chat/tests/test_models.py
  pytest.ini
  tests/test_config/test_load_config.py
  tests/test_context/test_hybrid_parallel.py
  tests/test_data/test_cifar10_dataset.py
  tests/test_data/test_data_parallel_sampler.py
  tests/test_data/test_deterministic_dataloader.py
  tests/test_utils/test_activation_checkpointing.py
Labels: DevOps, testing

#4457 [example] update resnet example result
  examples/images/resnet/README.md
  examples/images/resnet/train.py
Labels: example

#4458 [example] update bert example result
  examples/language/bert/README.md
  examples/language/bert/finetune.py
Labels: example

#4468 [doc] update gemini doc
  docs/source/en/features/zero_with_chunk.md
  docs/source/zh-Hans/features/zero_with_chunk.md
Labels: documentation

#4473 [example] update gemini related examples
  examples/images/dreambooth/test_ci.sh
  examples/images/dreambooth/train_dreambooth_colossalai.py
  examples/images/dreambooth/train_dreambooth_colossalai_lora.py
  examples/images/vit/vit_benchmark.py
  examples/images/vit/vit_train_demo.py
  examples/language/gpt/gemini/run_gemini.sh
  examples/language/gpt/gemini/test_ci.sh
  examples/language/gpt/gemini/train_gpt_demo.py
  examples/language/opt/opt_benchmark.py
  examples/language/opt/opt_train_demo.py
  examples/language/palm/train.py
Labels: example

#4480 [hotfix] fix bert in model zoo
  tests/kit/model_zoo/transformers/bert.py
  tests/test_booster/test_plugin/test_gemini_plugin.py
  tests/test_shardformer/test_model/test_shard_gpt2.py
Labels: bug

#4497 [hotfix] fix opt tutorial example
  examples/tutorial/opt/opt/run_clm.py
  examples/tutorial/opt/opt/test_ci.sh
Labels: example

#4527 [example] add llama2 example
  colossalai/cli/launcher/run.py
  colossalai/kernel/cuda_native/mha/mem_eff_attn.py
  examples/language/llama/README.md
  examples/language/llama2/README.md
  examples/language/llama2/attn.py
  examples/language/llama2/benchmark.py
  examples/language/llama2/data_utils.py
  examples/language/llama2/model_utils.py
  examples/language/llama2/performance_evaluator.py
  examples/language/llama2/pretrain.py
  examples/language/llama2/requirements.txt
  examples/language/llama2/scripts/benchmark_70B/3d.sh
  examples/language/llama2/scripts/benchmark_70B/gemini.sh
  examples/language/llama2/scripts/benchmark_70B/gemini_auto.sh
  examples/language/llama2/scripts/benchmark_7B/gemini.sh
  examples/language/llama2/scripts/benchmark_7B/gemini_auto.sh
  examples/language/llama2/test_ci.sh
Labels: example

#4541 [coati] update ci
  .github/workflows/run_chatgpt_examples.yml
  .github/workflows/run_chatgpt_unit_tests.yml
Labels: DevOps

#4386 [example] upgrade streamlit to 1.11.1
  examples/images/diffusion/requirements.txt
Labels: example

#4546 [devops] cancel previous runs in the PR
  .github/workflows/build_on_pr.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/doc_check_on_pr.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/example_check_on_pr.yml
Labels: DevOps
