Repository hpcaitech/ColossalAI, pull requests merged in 2023-05, with the labels that each got.

#3679 [chat] doc enhancement
  applications/Chat/examples/README.md
  applications/Chat/examples/example_data_reformat.py
Labels: chatgpt

#3610 [booster] gemini plugin support shard checkpoint
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/checkpoint_io/checkpoint_io_base.py
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/index_file.py
  colossalai/checkpoint_io/utils.py
  colossalai/zero/gemini/gemini_ddp.py
  pytest.ini
  tests/test_checkpoint_io/test_general_checkpoint_io.py
  tests/test_zero/test_gemini/test_zeroddp_state_dict_shard.py
Labels: Run Build and Test, API

#3693 [example] add finetune bert with booster example
  examples/tutorial/new_api/glue_bert/README.md
  examples/tutorial/new_api/glue_bert/data.py
  examples/tutorial/new_api/glue_bert/finetune.py
  examples/tutorial/new_api/glue_bert/test_ci.sh
Labels: example, API

#3663 [tensor] Refactor handle_trans_spec in DistSpecManager
  colossalai/tensor/dist_spec_mgr.py
Labels: Run Build and Test

#3694 [example] add train resnet/vit with booster example
  colossalai/_analyzer/__init__.py
  examples/tutorial/new_api/cifar_resnet/.gitignore
  examples/tutorial/new_api/cifar_resnet/README.md
  examples/tutorial/new_api/cifar_resnet/eval.py
  examples/tutorial/new_api/cifar_resnet/requirements.txt
  examples/tutorial/new_api/cifar_resnet/test_ci.sh
  examples/tutorial/new_api/cifar_resnet/train.py
  examples/tutorial/new_api/cifar_vit/README.md
  examples/tutorial/new_api/cifar_vit/requirements.txt
  examples/tutorial/new_api/cifar_vit/test_ci.sh
  examples/tutorial/new_api/cifar_vit/train.py
  examples/tutorial/new_api/glue_bert/README.md
  examples/tutorial/new_api/glue_bert/requirements.txt
  examples/tutorial/new_api/glue_bert/test_ci.sh
  examples/tutorial/new_api/test_ci.sh
  examples/tutorial/new_api/torch_ddp/README.md
  examples/tutorial/new_api/torch_ddp/train.py
Labels: example, API

#3706 [booster] update prepare dataloader method for plugin
  colossalai/booster/plugin/dp_plugin_base.py
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/booster/plugin/plugin_base.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  examples/tutorial/new_api/cifar_resnet/train.py
  examples/tutorial/new_api/cifar_vit/train.py
  examples/tutorial/new_api/glue_bert/data.py
  tests/test_booster/test_plugin/test_dp_plugin_base.py
Labels: Run Build and Test, API

#3709 [booster] fix no_sync method
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/booster/plugin/plugin_base.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  tests/test_booster/test_plugin/test_dp_plugin_base.py
  tests/test_booster/test_plugin/test_torch_ddp_plugin.py
Labels: bug, Run Build and Test, API

#3715 [booster] add tests for ddp and low level zero's checkpointio
  colossalai/testing/__init__.py
  colossalai/testing/comparison.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_checkpoint_io/test_general_checkpoint_io.py
  tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
  tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
Labels: Run Build and Test, API

#3707 fix some spelling error with tests/ colossalai/ etc.
  applications/Chat/coati/kernels/opt_attn.py
  colossalai/communication/p2p.py
  colossalai/communication/p2p_v2.py
  colossalai/context/process_group_initializer/initializer_sequence.py
  examples/tutorial/new_api/cifar_resnet/train.py
  examples/tutorial/new_api/cifar_vit/train.py
  op_builder/utils.py
  tests/components_to_test/albert.py
  tests/components_to_test/beit.py
  tests/components_to_test/bert.py
  tests/components_to_test/registry.py
  tests/test_utils/test_activation_checkpointing.py
  tests/test_utils/test_checkpoint_io/test_load.py
  tests/test_utils/test_checkpoint_io/test_merge.py
  tests/test_utils/test_checkpoint_io/test_redist.py
  tests/test_utils/test_checkpoint_io/test_save.py
  tests/test_utils/test_lazy_init/utils.py
Labels: Run Build and Test

#3727 [CI] fix typo with tests/ etc.
  tests/components_to_test/albert.py
  tests/test_booster/test_accelerator.py
  tests/test_booster/test_plugin/test_dp_plugin_base.py
  tests/test_data_pipeline_tensor_parallel/test_cifar_with_data_pipeline_tensor.py
  tests/test_data_pipeline_tensor_parallel/test_cifar_with_data_pipeline_tensor_v2.py
  tests/test_fx/test_codegen/test_activation_checkpoint_codegen.py
  tests/test_fx/test_codegen/test_nested_activation_checkpoint_codegen.py
  tests/test_fx/test_codegen/test_offload_codegen.py
  tests/test_layers/test_sequence/test_sequence.py
  tests/test_moe/test_kernel.py
  tests/test_tensor/model/test_model.py
  tests/test_trainer/test_pipeline/test_p2p.py
  tests/test_zero/test_gemini/test_chunkv2.py
Labels: Run Build and Test

#3735 [NFC] fix typo applications/ and colossalai/
  applications/Chat/examples/community/peft/README.md
  applications/Chat/inference/README.md
  applications/Chat/inference/benchmark.py
  colossalai/auto_parallel/README.md
  colossalai/auto_parallel/passes/runtime_preparation_pass.py
  colossalai/autochunk/autochunk_codegen.py
  colossalai/autochunk/trace_indice.py
  colossalai/checkpoint_io/index_file.py
  colossalai/checkpoint_io/utils.py
  colossalai/cli/check/check_installation.py
Labels: Run Build and Test

#3697 [booster] support torch fsdp plugin in booster
  colossalai/booster/plugin/__init__.py
  colossalai/booster/plugin/torch_fsdp_plugin.py
  colossalai/testing/utils.py
  tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
Labels: Run Build and Test, API

#3725 [devops] update torch version of CI
  .coveragerc
  .github/workflows/build_on_pr.yml
  .github/workflows/build_on_schedule.yml
  requirements/requirements-test.txt
  tests/test_analyzer/test_subclasses/test_flop_tensor.py
  tests/test_autochunk/test_autochunk_diffuser/test_autochunk_diffuser_utils.py
  tests/test_autochunk/test_autochunk_transformer/test_autochunk_gpt.py
  tests/test_autochunk/test_autochunk_transformer/test_autochunk_transformer_utils.py
  tests/test_autochunk/test_autochunk_vit/test_autochunk_vit_utils.py
  tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
  tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
  tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
  tests/test_cluster/test_device_mesh_manager.py
  tests/test_fx/test_tracer/test_timm_model/test_timm_model.py
  tests/test_utils/test_lazy_init/test_distribute.py
  tests/test_utils/test_lazy_init/test_models.py
  tests/test_utils/test_lazy_init/utils.py
Labels: Run Build and Test, DevOps, testing

#3744 [booster] removed models that fsdp not support in test
  tests/test_booster/test_plugin/test_torch_fsdp_plugin.py
Labels: Run Build and Test, API

#3742 [NFC] fix typo with colossalai/auto_parallel/tensor_shard
  colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py
  colossalai/auto_parallel/tensor_shard/node_handler/strategy/batch_norm_generator.py
  colossalai/auto_parallel/tensor_shard/node_handler/strategy/binary_elementwise_generator.py
  colossalai/auto_parallel/tensor_shard/node_handler/strategy/strategy_generator.py
  colossalai/auto_parallel/tensor_shard/solver/cost_graph.py
  colossalai/auto_parallel/tensor_shard/solver/graph_analysis.py
  colossalai/auto_parallel/tensor_shard/solver/solver.py
  colossalai/testing/pytest_wrapper.py
Labels: Run Build and Test

#3748 [devops] make build on PR run automatically
  .github/workflows/README.md
  .github/workflows/build_on_pr.yml
Labels: DevOps

#3751 [devops] fix ci for document check
  .github/workflows/doc_check_on_pr.yml
  docs/source/zh-Hans/features/1D_tensor_parallel.md
Labels: bug, DevOps

#3759 [chat] fix bugs in stage 3 training
  applications/Chat/coati/dataset/prompt_dataset.py
  applications/Chat/examples/README.md
  applications/Chat/examples/example_data_reformat.py
  applications/Chat/examples/generate_prompt_dataset.py
Labels: chatgpt

#3718 [doc] update booster tutorials
  docs/sidebars.json
  docs/source/en/basics/booster_api.md
  docs/source/en/basics/launch_colossalai.md
  docs/source/en/get_started/installation.md
  docs/source/zh-Hans/basics/booster_api.md
  docs/source/zh-Hans/basics/launch_colossalai.md
  docs/source/zh-Hans/get_started/installation.md
Labels: documentation, API

#3770 [doc] update hybrid parallelism doc
  docs/source/en/features/1D_tensor_parallel.md
  docs/source/en/features/2D_tensor_parallel.md
  docs/source/en/features/2p5D_tensor_parallel.md
  docs/source/en/features/3D_tensor_parallel.md
  docs/source/zh-Hans/features/1D_tensor_parallel.md
  docs/source/zh-Hans/features/2D_tensor_parallel.md
  docs/source/zh-Hans/features/2p5D_tensor_parallel.md
  docs/source/zh-Hans/features/3D_tensor_parallel.md
Labels: documentation

#3774 [amp] Add naive amp demo
  colossalai/booster/mixed_precision/__init__.py
  colossalai/booster/mixed_precision/fp16_naive.py
Labels: Run Build and Test, API

#3775 [plugin] torch ddp plugin supports sharded model checkpoint
  colossalai/booster/plugin/torch_ddp_plugin.py
  colossalai/checkpoint_io/checkpoint_io_base.py
  colossalai/checkpoint_io/utils.py
  tests/test_booster/test_plugin/test_low_level_zero_plugin.py
  tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
Labels: API

#3763 [doc] add tutorial for cluster utils
  docs/sidebars.json
  docs/source/en/features/cluster_utils.md
  docs/source/zh-Hans/features/cluster_utils.md
Labels: documentation

#3758 [doc] add tutorial for booster plugins
  docs/sidebars.json
  docs/source/en/basics/booster_plugins.md
  docs/source/zh-Hans/basics/booster_plugins.md
Labels: documentation, API

#3756 [NFC] fix typo colossalai/amp auto_parallel autochunk
  colossalai/amp/torch_amp/_grad_scaler.py
  colossalai/auto_parallel/meta_profiler/meta_registry/linear.py
  colossalai/auto_parallel/passes/runtime_apply_pass.py
  colossalai/auto_parallel/passes/runtime_preparation_pass.py
  colossalai/autochunk/trace_flow.py
  colossalai/autochunk/trace_indice.py
Labels: Run Build and Test

#3782 [devops] fix doc test on pr
  .github/workflows/doc_test_on_pr.yml
Labels: bug, DevOps

#3780 [plugin] a workaround for zero plugins' optimizer checkpoint
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  tests/test_checkpoint_io/test_gemini_checkpoint_io.py
  tests/test_checkpoint_io/test_low_level_zero_checkpoint_io.py
  tests/test_checkpoint_io/test_torch_ddp_checkpoint_io.py
  tests/test_checkpoint_io/utils.py
Labels: API

#3789 [doc] add booster docstring and fix autodoc
  colossalai/booster/booster.py
  docs/source/en/basics/booster_api.md
  docs/source/en/features/cluster_utils.md
  docs/source/zh-Hans/basics/booster_api.md
  docs/source/zh-Hans/features/cluster_utils.md
Labels: documentation

#3754 [doc] add deprecated warning on doc Basics section
  docs/source/en/basics/colotensor_concept.md
  docs/source/en/basics/configure_parallelization.md
  docs/source/en/basics/define_your_config.md
  docs/source/en/basics/engine_trainer.md
  docs/source/en/basics/initialize_features.md
  docs/source/en/basics/model_checkpoint.md
  docs/source/zh-Hans/basics/colotensor_concept.md
  docs/source/zh-Hans/basics/configure_parallelization.md
  docs/source/zh-Hans/basics/define_your_config.md
  docs/source/zh-Hans/basics/engine_trainer.md
  docs/source/zh-Hans/basics/initialize_features.md
  docs/source/zh-Hans/basics/model_checkpoint.md
Labels: documentation

#3778 [doc] update gradient cliping document
  docs/sidebars.json
  docs/source/en/features/gradient_clipping.md
  docs/source/en/features/gradient_clipping_with_booster.md
  docs/source/zh-Hans/features/gradient_clipping.md
  docs/source/zh-Hans/features/gradient_clipping_with_booster.md
Labels: documentation, API

#3771 [doc] update gradient accumulation
  docs/sidebars.json
  docs/source/en/features/gradient_accumulation.md
  docs/source/en/features/gradient_accumulation_with_booster.md
  docs/source/zh-Hans/features/gradient_accumulation.md
  docs/source/zh-Hans/features/gradient_accumulation_with_booster.md
Labels: documentation, API

#3801 [workflow] enable testing for develop & feature branch
  .github/workflows/build_on_pr.yml
  .github/workflows/doc_check_on_pr.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/example_check_on_pr.yml
Labels: enhancement, testing

#3799 [test] fixed lazy init test import error
  tests/test_utils/test_lazy_init/lazy_init_utils.py
  tests/test_utils/test_lazy_init/test_distribute.py
  tests/test_utils/test_lazy_init/test_models.py
Labels: bug, testing

#3783 [API] add docstrings and initialization to apex amp, naive amp
  colossalai/booster/mixed_precision/fp16_apex.py
  colossalai/booster/mixed_precision/fp16_naive.py
Labels: API

#3813 [doc] add warning about fsdp plugin
  docs/source/en/basics/booster_plugins.md
  docs/source/zh-Hans/basics/booster_plugins.md
Labels: documentation

#3815 [workflow] enblaed doc build from a forked repo
  .github/workflows/doc_build_after_merge.yml
Labels: bug, testing

#3810 [doc] update amp document
  docs/sidebars.json
  docs/source/en/features/gradient_accumulation_with_booster.md
  docs/source/en/features/gradient_clipping_with_booster.md
  docs/source/en/features/mixed_precision_training.md
  docs/source/en/features/mixed_precision_training_with_booster.md
  docs/source/zh-Hans/features/gradient_accumulation_with_booster.md
  docs/source/zh-Hans/features/gradient_clipping_with_booster.md
  docs/source/zh-Hans/features/mixed_precision_training.md
  docs/source/zh-Hans/features/mixed_precision_training_with_booster.md
Labels: documentation, API

#3809 [evaluate] update readme.md for evaluation pipeline
  applications/Chat/evaluate/README.md
Labels: documentation

#3807 [evaluate] support gpt evaluation
  applications/Chat/evaluate/eval.py
  applications/Chat/evaluate/eval.sh
  applications/Chat/evaluate/evaluate.py
  applications/Chat/evaluate/evaluate.sh
  applications/Chat/evaluate/evaluator.py
  applications/Chat/evaluate/generate_answers.py
  applications/Chat/evaluate/generate_answers.sh
  applications/Chat/evaluate/generate_gpt35_answers.py
  applications/Chat/evaluate/generate_gpt35_answers.sh
  applications/Chat/evaluate/gpt_evaluate.py
  applications/Chat/evaluate/merge.py
  applications/Chat/evaluate/requirements.txt
  applications/Chat/evaluate/utils.py
  applications/Chat/requirements.txt
Labels: code reviewing

#3820 [evaluate] add Chinese example for config, battle prompt and evaluation prompt file
  applications/Chat/evaluate/config/config_cn.json
  applications/Chat/evaluate/prompt/battle_prompt/battle_prompt_cn.json
  applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_cn.json
Labels: code reviewing

#3822 [evaluate] remove GPT-4 config
  applications/Chat/evaluate/config/config_cn.json
Labels: code reviewing

#3823 [evaluate] remove sample folder
  applications/Chat/evaluate/sample/questions.json
Labels: code reviewing

#3825 [workflow] changed to doc build to be on schedule and release
  .github/workflows/doc_build_on_schedule_after_release.yml
Labels: DevOps

#3821 [evaluation] add automatic evaluation pipeline
  applications/Chat/evaluate/README.md
  applications/Chat/evaluate/config/config_cn.json
  applications/Chat/evaluate/eval.py
  applications/Chat/evaluate/eval.sh
  applications/Chat/evaluate/evaluate.py
  applications/Chat/evaluate/evaluate.sh
  applications/Chat/evaluate/evaluator.py
  applications/Chat/evaluate/generate_answers.py
  applications/Chat/evaluate/generate_answers.sh
  applications/Chat/evaluate/generate_gpt35_answers.py
  applications/Chat/evaluate/generate_gpt35_answers.sh
  applications/Chat/evaluate/gpt_evaluate.py
  applications/Chat/evaluate/merge.py
  applications/Chat/evaluate/metrics.py
  applications/Chat/evaluate/prompt/battle_prompt/battle_prompt_cn.json
  applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_cn.json
  applications/Chat/evaluate/requirements.txt
  applications/Chat/evaluate/sample/questions.json
  applications/Chat/evaluate/utils.py
Labels: chatgpt

#3827 [shardformer] updated readme
  colossalai/shardformer/README.md
Labels: documentation, shardformer

#3806 [workflow] fixed testmon cache in build CI
  .github/workflows/build_on_pr.yml
  .gitignore
  requirements/requirements-test.txt
Labels: bug, testing

#3828 [shardformer] refactored the user api
  colossalai/shardformer/README.md
  colossalai/shardformer/shard/__init__.py
  colossalai/shardformer/shard/shard_config.py
  colossalai/shardformer/shard/sharder.py
  colossalai/shardformer/shard/shardmodel.py
  colossalai/shardformer/shard/slicer.py
  colossalai/shardformer/test/test.py
Labels: enhancement, shardformer

#3838 [dtensor] polish sharding spec docstring
  colossalai/tensor/d_tensor/sharding_spec.py
Labels: documentation

#3841 [workflow] supported test on CUDA 10.2
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  README.md
  docs/source/en/get_started/installation.md
  docs/source/zh-Hans/get_started/installation.md
Labels: bug, testing

#3830 [release] bump to v0.3.0
  version.txt
Labels: release

#3850 [doc] update nvme offload documents.
  docs/source/en/features/nvme_offload.md
  docs/source/zh-Hans/features/nvme_offload.md
Labels: documentation, API

#3862 [evaluation] improvement on evaluation
  applications/Chat/evaluate/README.md
  applications/Chat/evaluate/config/config_cn.json
  applications/Chat/evaluate/eval.py
  applications/Chat/evaluate/evaluator.py
  applications/Chat/evaluate/gpt_evaluate.py
  applications/Chat/evaluate/prompt/evaluation_prompt/evaluation_prompt_cn.json
  applications/Chat/evaluate/utils.py
Labels: code reviewing

#3868 [example] update gemini examples
  examples/language/gpt/gemini/test_ci.sh
  examples/language/gpt/gemini/train_gpt_demo.py
Labels: example, API

#3869 [bf16] implement mixed precision mixin and add bf16 support for low level zero
  colossalai/amp/naive_amp/mixed_precision_mixin/__init__.py
  colossalai/amp/naive_amp/mixed_precision_mixin/base.py
  colossalai/amp/naive_amp/mixed_precision_mixin/bf16.py
  colossalai/amp/naive_amp/mixed_precision_mixin/fp16.py
  colossalai/zero/low_level/low_level_optim.py
  tests/test_zero/test_low_level/test_grad_acc.py
  tests/test_zero/test_low_level/test_zero1_2.py
Labels: enhancement
