Repository hpcaitech/ColossalAI, pull requests merged in 2023-02, with the labels that each got.

#2538 [autochunk] support multi outputs chunk search
  colossalai/autochunk/autochunk_codegen.py
  colossalai/autochunk/estimate_memory.py
  colossalai/autochunk/reorder_graph.py
  colossalai/autochunk/search_chunk.py
  colossalai/autochunk/select_chunk.py
  colossalai/autochunk/trace_flow.py
  colossalai/autochunk/trace_indice.py
  colossalai/autochunk/utils.py
  tests/test_autochunk/test_alphafold/test_alphafold_utils.py
  tests/test_autochunk/test_alphafold/test_evoformer_block.py
  tests/test_autochunk/test_alphafold/test_evoformer_stack.py
  tests/test_autochunk/test_alphafold/test_extramsa_block.py
  tests/test_autochunk/test_transformer/test_autochunk_gpt.py
  tests/test_autochunk/test_transformer/test_transformer_utils.py
Labels: Run Build and Test

#2543 [autochunk] add benchmark for transformer and alphafold
  tests/test_autochunk/test_autochunk_alphafold/benchmark_autochunk_alphafold.py
  tests/test_autochunk/test_autochunk_alphafold/test_autochunk_alphafold_utils.py
  tests/test_autochunk/test_autochunk_alphafold/test_autochunk_evoformer_block.py
  tests/test_autochunk/test_autochunk_alphafold/test_autochunk_evoformer_stack.py
  tests/test_autochunk/test_autochunk_alphafold/test_autochunk_extramsa_block.py
  tests/test_autochunk/test_autochunk_diffuser/test_autochunk_diffuser_utils.py
  tests/test_autochunk/test_autochunk_diffuser/test_autochunk_unet.py
  tests/test_autochunk/test_autochunk_transformer/benchmark_autochunk_transformer.py
  tests/test_autochunk/test_autochunk_transformer/test_autochunk_gpt.py
  tests/test_autochunk/test_autochunk_transformer/test_autochunk_transformer_utils.py
Labels: Run Build and Test

#2544 [fx] support unet metainfo prop
  colossalai/fx/_meta_registrations.py
  colossalai/fx/profiler/opcount.py
Labels: Run Build and Test

#2545 [hotfix] fix zero ddp warmup check
  colossalai/gemini/gemini_mgr.py
  colossalai/nn/parallel/data_parallel.py
Labels: bug

#2550 [doc] added pull request template
  .github/pull_request_template.md
Labels: documentation

#2549 [kernel] fixed repeated loading of kernels
  colossalai/kernel/cuda_native/__init__.py
  colossalai/kernel/cuda_native/layer_norm.py
  colossalai/kernel/cuda_native/scaled_softmax.py
  op_builder/builder.py
Labels: Run Build and Test

#2556 [doc] fixed the typo in pr template
  .github/pull_request_template.md
Labels: documentation

#2552 [doc] updated the CHANGE_LOG.md for github release page
  CHANGE_LOG.md
Labels: documentation

#2537 [polish] polish ColoTensor and its submodules
  colossalai/tensor/colo_parameter.py
  colossalai/tensor/colo_tensor.py
  colossalai/tensor/compute_spec.py
  colossalai/tensor/distspec.py
  colossalai/tensor/process_group.py
  colossalai/utils/model/colo_init_context.py
Labels: Run Build and Test

#2564 [workflow] added contributor and user-engagement report
  .github/workflows/report_leaderboard_to_lark.yml
  .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
Labels: DevOps

#2567 [workflow] fixed typos in the leaderboard workflow
  .github/workflows/report_leaderboard_to_lark.yml
Labels: bug

#2577 [doc] fixed issue link in pr template
  .github/pull_request_template.md
Labels: documentation

#2554 [workflow] fixed example check workflow
  .github/workflows/README.md
  .github/workflows/example_check_on_dispatch.yml
  .github/workflows/example_check_on_pr.yml
  .github/workflows/example_check_on_schedule.yml
Labels: bug, DevOps, example

#2558 [workflow] adjust the GPU memory threshold for scheduled unit test
  .github/workflows/build_on_pr.yml
  .github/workflows/build_on_schedule.yml
Labels: DevOps

#2560 [workflow] refactored compatibility test workflow for maintenability
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/compatiblity_test_on_schedule.yml
Labels: DevOps

#2572 [workflow] added discussion stats to community report
  .github/workflows/report_leaderboard_to_lark.yml
  .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
Labels: DevOps

#2578 [setup] fixed inconsistent version meta
  setup.py
Labels: bug

#2574 [workflow] added notification if scheduled build fails
  .github/workflows/build_on_schedule.yml
  .github/workflows/scripts/send_message_to_lark.py
  test.sh
Labels: DevOps

#2586 [workflow] hook compatibility test failure to lark
  .github/workflows/compatiblity_test_on_schedule.yml
Labels: DevOps

#2589 [workflow] fixed the typo in the example check workflow
  .github/workflows/example_check_on_schedule.yml
Labels: DevOps, example

#2591 [workflow] added test-pypi check before release
  .github/workflows/release_nightly_on_schedule.yml
  .github/workflows/release_pypi_after_merge.yml
  .github/workflows/release_test_pypi_before_merge.yml
Labels: DevOps

#2594 [workflow] hooked docker release with lark
  .github/workflows/release_docker_after_merge.yml
Labels: DevOps

#2596 [workflow] hooked pypi release with lark
  .github/workflows/auto_example_check.yml
  .github/workflows/auto_release_bdist.yml
  .github/workflows/draft_github_release_post_after_merge.yml
  .github/workflows/release_nightly_on_schedule.yml
  .github/workflows/release_pypi_after_merge.yml
Labels: DevOps

#2598 [workflow] added cuda extension build test before release
  .bdist.json
  .cuda_ext.json
  .github/workflows/cuda_ext_check_before_merge.yml
  .github/workflows/release_bdist.yml
Labels: DevOps

#2600 [doc] updated readme for CI/CD
  .github/workflows/README.md
  .github/workflows/example_check_on_pr.yml
  .github/workflows/report_test_coverage.yml
  .github/workflows/scripts/build_colossalai_wheel.py
  .github/workflows/scripts/build_colossalai_wheel.sh
Labels: documentation, DevOps

#2602 [release] v0.2.1
  .github/workflows/release_test_pypi_before_merge.yml
  version.txt
Labels: release

#2604 [workflow] fixed broken release workflows
  .github/workflows/release_docker_after_merge.yml
  .github/workflows/release_pypi_after_merge.yml
  .github/workflows/scripts/generate_release_draft.py
Labels: bug, DevOps

#2614 [workflow] fixed the test coverage report
  .github/workflows/report_test_coverage.yml
  test.sh
Labels: bug

#2608 [test] fixed the triton version for testing
  .github/workflows/build_on_pr.yml
  colossalai/amp/apex_amp/apex_amp.py
  requirements/requirements-test.txt
Labels: bug, Run Build and Test

#2618 [build] fixed the doc build process
  requirements/requirements.txt
Labels: bug

#2623 [doc] fixed broken badge
  README-zh-Hans.md
  README.md
Labels: bug

#2625 [tutorial] added energonai to opt inference requirements
  examples/tutorial/opt/inference/requirements.txt
Labels: example

#2584 [autoparallel] Patch meta information of `torch.matmul`
  colossalai/auto_parallel/meta_profiler/meta_registry/linear.py
  colossalai/auto_parallel/tensor_shard/node_handler/matmul_handler.py
  colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py
  colossalai/fx/profiler/opcount.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_matmul_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_matmul_handler.py
Labels: Run Build and Test, auto-parallel

#2637 [doc] removed pre-built wheel installation from readme
  README-zh-Hans.md
  README.md
Labels: documentation

#2626 [autoparallel] adapt autoparallel tests with latest api
  colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py
  colossalai/auto_parallel/tensor_shard/solver/cost_graph.py
  tests/test_auto_parallel/test_tensor_shard/test_bias_addition_forward.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_gpt2_performance.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_runtime_with_gpt_modules.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/utils.py
  tests/test_auto_parallel/test_tensor_shard/test_resnet_block_runtime.py
  tests/test_auto_parallel/test_tensor_shard/test_shape_consistency_pass.py
Labels: Run Build and Test, auto-parallel

#2613 [autoparallel] add overlap option
  colossalai/auto_parallel/passes/runtime_preparation_pass.py
  colossalai/auto_parallel/tensor_shard/initialize.py
Labels: Run Build and Test, auto-parallel

#2656 [doc] added docusaurus-based version control
  docs/sidebars.js
  docs/versions.json
Labels: documentation

#2657 [doc] fixed compatiblity with docusaurus
  docs/source/en/Colossal-Auto/get_started/run_demo.md
  docs/source/zh-Hans/Colossal-Auto/feature/auto_checkpoint.md
  docs/source/zh-Hans/Colossal-Auto/feature/device_mesh.md
  docs/source/zh-Hans/Colossal-Auto/feature/shape_consistency.md
  docs/source/zh-Hans/Colossal-Auto/feature/tracer.md
  docs/source/zh-Hans/Colossal-Auto/get_started/installation.md
  docs/source/zh-Hans/Colossal-Auto/get_started/introduction.md
  docs/source/zh-Hans/Colossal-Auto/get_started/run_demo.md
  docs/source/zh-Hans/advanced_tutorials/add_your_parallel.md
  docs/source/zh-Hans/advanced_tutorials/define_your_own_parallel_model.md
  docs/source/zh-Hans/advanced_tutorials/integrate_mixture_of_experts_into_your_model.md
  docs/source/zh-Hans/advanced_tutorials/meet_gemini.md
  docs/source/zh-Hans/advanced_tutorials/opt_service.md
  docs/source/zh-Hans/advanced_tutorials/parallelize_your_training_like_Megatron.md
  docs/source/zh-Hans/advanced_tutorials/train_gpt_using_hybrid_parallelism.md
  docs/source/zh-Hans/advanced_tutorials/train_vit_using_pipeline_parallelism.md
  docs/source/zh-Hans/advanced_tutorials/train_vit_with_hybrid_parallelism.md
  docs/source/zh-Hans/basics/colotensor_concept.md
  docs/source/zh-Hans/basics/command_line_tool.md
  docs/source/zh-Hans/basics/configure_parallelization.md
  docs/source/zh-Hans/basics/define_your_config.md
  docs/source/zh-Hans/basics/engine_trainer.md
  docs/source/zh-Hans/basics/initialize_features.md
  docs/source/zh-Hans/basics/launch_colossalai.md
  docs/source/zh-Hans/basics/model_checkpoint.md
  docs/source/zh-Hans/concepts/colossalai_overview.md
  docs/source/zh-Hans/concepts/distributed_training.md
  docs/source/zh-Hans/concepts/paradigms_of_parallelism.md
  docs/source/zh-Hans/features/1D_tensor_parallel.md
  docs/source/zh-Hans/features/2D_tensor_parallel.md
  docs/source/zh-Hans/features/2p5D_tensor_parallel.md
  docs/source/zh-Hans/features/3D_tensor_parallel.md
  docs/source/zh-Hans/features/gradient_accumulation.md
  docs/source/zh-Hans/features/gradient_clipping.md
  docs/source/zh-Hans/features/gradient_handler.md
  docs/source/zh-Hans/features/mixed_precision_training.md
  docs/source/zh-Hans/features/nvme_offload.md
  docs/source/zh-Hans/features/pipeline_parallel.md
  docs/source/zh-Hans/features/zero_with_chunk.md
  docs/source/zh-Hans/get_started/installation.md
  docs/source/zh-Hans/get_started/reading_roadmap.md
  docs/source/zh-Hans/get_started/run_demo.md
Labels: documentation

#2659 [workflow] fixed gpu memory check condition
  .github/workflows/build_on_schedule.yml
Labels: DevOps

#2647 [autoparallel] Patch meta information of `torch.nn.LayerNorm`
  colossalai/auto_parallel/meta_profiler/meta_registry/norm.py
  colossalai/auto_parallel/tensor_shard/node_handler/layer_norm_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_batchnorm_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_matmul_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_norm_metainfo.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/utils.py
Labels: Run Build and Test, auto-parallel

#2665 [Docs] layout converting management
  docs/source/en/Colossal-Auto/feature/layout_converting_management.md
  docs/source/en/Colossal-Auto/feature/shape_consistency.md
  docs/source/zh-Hans/Colossal-Auto/feature/layout_converting_management.md
  docs/source/zh-Hans/Colossal-Auto/feature/shape_consistency.md
Labels: auto-parallel

#2669 [release] v0.2.3
  docs/sidebars.js
  docs/sidebars.json
  docs/versions.json
  version.txt
Labels: release

#2672 [dooc] fixed the sidebar itemm key
  docs/source/en/sidebar_category_translation.json
  docs/source/zh-Hans/sidebar_category_translation.json
Labels: documentation

#2671 [gemini] add fake_release_chunk for keep-gathered chunk in the infere…
  colossalai/gemini/chunk/manager.py
  colossalai/nn/parallel/data_parallel.py
  tests/test_gemini/update/test_inference.py
Labels: bug, Run Build and Test, gemini

#2675 [workflow] added doc build test
  .github/workflows/check_doc_on_pr.yml
Labels: documentation, DevOps

#2674 [autoparallel] Patch meta information of `torch.nn.functional.softmax` and `torch.nn.Softmax`
  colossalai/auto_parallel/meta_profiler/meta_registry/activation.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_activation_metainfo.py
Labels: Run Build and Test, auto-parallel

#2678 [workflow] added trigger to build doc upon release
  .github/workflows/doc_build_after_merge.yml
  .github/workflows/doc_check_on_pr.yml
Labels: documentation, DevOps

#2680 [workflow] fixed communtity report ranking
  .github/workflows/scripts/generate_leaderboard_and_send_to_lark.py
Labels: DevOps

#2683 [gemini] fix colo_init_context
  colossalai/utils/model/colo_init_context.py
Labels: bug, gemini

#2681 [hotfix] only append parameters with gradients
  colossalai/zero/sharded_optim/low_level_optim.py
Labels: Run Build and Test

#2691 [release] update version
  version.txt
Labels: release

#2664 [autoparallel] remove deprecated codes
  colossalai/auto_parallel/tensor_shard/deprecated/__init__.py
  colossalai/auto_parallel/tensor_shard/deprecated/_utils.py
  colossalai/auto_parallel/tensor_shard/deprecated/constants.py
  colossalai/auto_parallel/tensor_shard/deprecated/cost_graph.py
  colossalai/auto_parallel/tensor_shard/deprecated/graph_analysis.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/__init__.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/batch_norm_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/bcast_op_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/conv_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/dot_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/embedding_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/layer_norm_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/operator_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/reshape_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/strategy_generator.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/unary_elementwise_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/op_handler/where_handler.py
  colossalai/auto_parallel/tensor_shard/deprecated/options.py
  colossalai/auto_parallel/tensor_shard/deprecated/sharding_strategy.py
  colossalai/auto_parallel/tensor_shard/deprecated/solver.py
  colossalai/auto_parallel/tensor_shard/deprecated/strategies_constructor.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_cost_graph.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_batch_norm_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_bcast_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_bcast_matmul.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_conv_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_dot_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_layer_norm_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_reshape_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_op_handler/test_deprecated_where_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_shape_consistency_pass.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_solver.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_solver_with_gpt.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_solver_with_mlp.py
  tests/test_auto_parallel/test_tensor_shard/test_deprecated/test_deprecated_strategies_constructor.py
Labels: Run Build and Test, auto-parallel

#2711 [workflow] fixed tensor-nvme build caching
  .github/workflows/build_on_pr.yml
Labels: bug, Run Build and Test, DevOps

#2644 [autoparallel] refactor runtime pass
  colossalai/auto_parallel/passes/constants.py
  colossalai/auto_parallel/passes/runtime_preparation_pass.py
  tests/test_auto_parallel/test_pass/test_node_converting_pass.py
  tests/test_auto_parallel/test_pass/test_size_value_converting_pass.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_linear_handler.py
Labels: Run Build and Test, auto-parallel

#2713 [devops] add chatgpt ci
  .github/workflows/run_chatgpt_examples.yml
  .github/workflows/run_chatgpt_unit_tests.yml
Labels: DevOps, chatgpt

#2715 [doc] updated documentation version list
  .github/workflows/doc_build_after_merge.yml
  docs/versions.json
Labels: documentation

#2696 [autoparallel] add shard option
  colossalai/auto_parallel/tensor_shard/initialize.py
  colossalai/auto_parallel/tensor_shard/node_handler/__init__.py
  colossalai/auto_parallel/tensor_shard/node_handler/node_handler.py
  colossalai/auto_parallel/tensor_shard/node_handler/option.py
  colossalai/auto_parallel/tensor_shard/options.py
  colossalai/auto_parallel/tensor_shard/solver/__init__.py
  colossalai/auto_parallel/tensor_shard/solver/options.py
  colossalai/auto_parallel/tensor_shard/solver/solver.py
  colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_solver_with_gpt_module.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/utils.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_shard_option.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
  tests/test_auto_parallel/test_tensor_shard/test_param_resharding_cost.py
  tests/test_auto_parallel/test_tensor_shard/test_solver_with_resnet_v2.py
Labels: Run Build and Test, auto-parallel

#2717 [chatgpt] optimize generation kwargs
  .github/workflows/run_chatgpt_examples.yml
  .github/workflows/run_chatgpt_unit_tests.yml
  applications/ChatGPT/benchmarks/benchmark_gpt_dummy.py
  applications/ChatGPT/benchmarks/benchmark_opt_lora_dummy.py
  applications/ChatGPT/chatgpt/trainer/ppo.py
  applications/ChatGPT/examples/train_dummy.py
  applications/ChatGPT/examples/train_prompts.py
Labels: enhancement, chatgpt

#2730 [doc] updated documentation version list
  docs/versions.json
Labels: documentation

#2687 [zero] Update method of grad store
  colossalai/zero/sharded_optim/bookkeeping/gradient_store.py
  colossalai/zero/sharded_optim/low_level_optim.py
Labels: Run Build and Test

#2699 [autoparallel] distinguish different parallel strategies
  colossalai/auto_parallel/tensor_shard/node_handler/linear_handler.py
  colossalai/auto_parallel/tensor_shard/node_handler/strategy/matmul_strategy_generator.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_runtime_with_gpt_modules.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_permute_and_transpose_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_softmax_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_split_handler.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/test_view_handler.py
Labels: Run Build and Test, auto-parallel

#2741 [chatgpt]fix train_rm bug with lora
  applications/ChatGPT/chatgpt/trainer/rm.py
Labels: bug, chatgpt

#2742 [chatgpt] support colossalai strategy to train rm
  applications/ChatGPT/chatgpt/trainer/rm.py
  applications/ChatGPT/examples/train_dummy.sh
  applications/ChatGPT/examples/train_prompts.sh
  applications/ChatGPT/examples/train_reward_model.py
  applications/ChatGPT/examples/train_rm.sh
Labels: bug, chatgpt

#2747 [doc] add opt service doc
  docs/sidebars.json
  docs/versions.json
Labels: documentation

#2767 [chatgpt] disable shard init for colossalai
  applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py
Labels: bug, chatgpt

#2775 Don't use `torch._six`
  colossalai/utils/common.py
  colossalai/zero/sharded_optim/_utils.py
Labels: API

#2777 [zero] fix wrong import in `zero/sharded_optim/_utils.py`
  colossalai/zero/sharded_optim/_utils.py
Labels: bug

#2760 [autoparallel] Patch meta information of `torch.nn.Embedding`
  colossalai/auto_parallel/meta_profiler/meta_registry/__init__.py
  colossalai/auto_parallel/meta_profiler/meta_registry/embedding.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_embedding_metainfo.py
Labels: Run Build and Test, auto-parallel

#2766 [chatgpt] startegy add prepare method
  applications/ChatGPT/benchmarks/benchmark_gpt_dummy.py
  applications/ChatGPT/benchmarks/benchmark_opt_lora_dummy.py
  applications/ChatGPT/chatgpt/trainer/ppo.py
  applications/ChatGPT/chatgpt/trainer/strategies/base.py
  applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py
  applications/ChatGPT/chatgpt/trainer/strategies/ddp.py
  applications/ChatGPT/chatgpt/trainer/strategies/naive.py
  applications/ChatGPT/examples/train_dummy.py
  applications/ChatGPT/examples/train_prompts.py
Labels: enhancement, chatgpt

#2792 [chatgpt] update readme about checkpoint
  applications/ChatGPT/README.md
Labels: documentation, chatgpt

#2796 [hotfix] add correct device for fake_param
  colossalai/nn/optimizer/zero_optimizer.py
  tests/test_gemini/update/test_zerooptim_state_dict.py
Labels: Run Build and Test

#2813 [autoparallel] rotor solver refactor
  colossalai/auto_parallel/checkpoint/ckpt_solver_rotor.c
  colossalai/auto_parallel/checkpoint/ckpt_solver_rotor.py
Labels: auto-parallel

#2824 [exmaple] add bert and albert
  examples/language/bert/run_gemini.sh
  examples/language/bert/test_ci.sh
  examples/language/bert/train_bert_demo.py
Labels: Run Build and Test

#2797 [chatgpt] add test checkpoint
  applications/ChatGPT/tests/test_checkpoint.py
  applications/ChatGPT/tests/test_data.py
Labels: chatgpt

#2789 [autoparallel] Patch tensor related operations meta information
  colossalai/auto_parallel/meta_profiler/meta_registry/__init__.py
  colossalai/auto_parallel/meta_profiler/meta_registry/pooling.py
  colossalai/auto_parallel/meta_profiler/meta_registry/tensor.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_tensor_metainfo.py
Labels: Run Build and Test, auto-parallel

#2773 [autoparallel] Patch meta information of `torch.tanh()` and `torch.nn.Dropout`
  colossalai/auto_parallel/meta_profiler/meta_registry/activation.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_activation_metainfo.py
Labels: Run Build and Test, auto-parallel

#2822 [autoparallel] Patch meta information of `torch.where`
  colossalai/auto_parallel/meta_profiler/meta_registry/__init__.py
  colossalai/auto_parallel/meta_profiler/meta_registry/where.py
  tests/test_auto_parallel/test_tensor_shard/test_metainfo/test_where_metainfo.py
Labels: Run Build and Test, auto-parallel

#2823 [autoparallel] Patch meta information for nodes that will not be handled by SPMD solver
  colossalai/auto_parallel/meta_profiler/meta_registry/__init__.py
  colossalai/auto_parallel/meta_profiler/meta_registry/non_spmd.py
Labels: Run Build and Test, auto-parallel

#2867 [hotfix] fix chunk size can not be divided
  colossalai/gemini/chunk/manager.py
  colossalai/gemini/chunk/search_utils.py
Labels: bug, Run Build and Test

#2692 [nn/parallel/data_parallel.py]: Rename "_pre_bacward" method of ZeroDDP to "_pre_backward"
  colossalai/nn/parallel/data_parallel.py
Labels: Run Build and Test

#2876 [chatgpt]gpt-2& opt rm training support
  applications/ChatGPT/chatgpt/nn/bloom_rm.py
  applications/ChatGPT/chatgpt/nn/gpt_rm.py
  applications/ChatGPT/chatgpt/nn/opt_rm.py
  applications/ChatGPT/examples/train_reward_model.py
  applications/ChatGPT/examples/train_rm.sh
Labels: chatgpt

#2854 [autoparallel] find repeat blocks
  colossalai/auto_parallel/tensor_shard/utils/factory.py
  tests/test_auto_parallel/test_pass/__init__.py
  tests/test_auto_parallel/test_tensor_shard/test_find_repeat_block.py
Labels: Run Build and Test, auto-parallel

#2754 [hotfix] fix autoparallel compatibility test issues
  colossalai/auto_parallel/tensor_shard/initialize.py
  tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_ddp.py
  tests/test_auto_parallel/test_tensor_shard/test_compatibility_with_gemini.py
Labels: Run Build and Test, auto-parallel

#2837 [hotfix]: Remove math.prod dependency
  colossalai/nn/_ops/view.py
  colossalai/tensor/colo_tensor.py
Labels: Run Build and Test

#2895 [workflow] moved pre-commit to post-commit
  .github/workflows/README.md
  .github/workflows/post_commit.yml
  .github/workflows/report_precommit_failure.yml
Labels: DevOps

#2869 [zero] trivial zero optimizer refactoring
  colossalai/zero/sharded_optim/bookkeeping/gradient_store.py
  colossalai/zero/sharded_optim/low_level_optim.py
Labels: Run Build and Test

#2920 [hotfix] fixed using zero with tp cannot access weight correctly
  colossalai/nn/layer/colossalai_layer/_utils.py
  colossalai/nn/layer/colossalai_layer/dropout.py
Labels: Run Build and Test

#2925 [utils] Specify the free port search exception.
  colossalai/utils/common.py
Labels: Run Build and Test

#2912 [autoparallel] apply repeat block to reduce solving time
  colossalai/auto_parallel/tensor_shard/initialize.py
  colossalai/auto_parallel/tensor_shard/solver/solver.py
  colossalai/auto_parallel/tensor_shard/solver/strategies_constructor.py
  tests/test_auto_parallel/test_tensor_shard/test_gpt/test_solver_with_gpt_module.py
  tests/test_auto_parallel/test_tensor_shard/test_node_handler/utils.py
  tests/test_auto_parallel/test_tensor_shard/test_solver_with_resnet_v2.py
Labels: Run Build and Test, auto-parallel

#2929 [workflow] added auto doc test on PR
  .github/workflows/doc_check_on_pr.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/doc_test_on_schedule.yml
  docs/requirements-doc-test.txt
  docs/source/en/get_started/installation.md
Labels: documentation, DevOps

#2935 [doc] added readme for documentation
  docs/README.md
Labels: documentation
