Repository hpcaitech/ColossalAI, pull requests merged in 2024-01, with the labels that each got.

#5217 [devops] update torch versoin in ci
  .github/workflows/build_on_pr.yml
  .github/workflows/build_on_schedule.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/doc_test_on_schedule.yml
  .github/workflows/example_check_on_dispatch.yml
  .github/workflows/example_check_on_pr.yml
  .github/workflows/example_check_on_schedule.yml
Labels: DevOps

#5192 [kernel] Add triton kernel for context attention without padding
  colossalai/kernel/triton/__init__.py
  colossalai/kernel/triton/context_attn_unpad.py
  tests/test_infer_ops/triton/test_context_attn_unpad.py
Labels: enhancement

#5249 [kernel] Add flash decoding triton kernel for blocked kv cache
  colossalai/kernel/triton/__init__.py
  colossalai/kernel/triton/context_attn_unpad.py
  colossalai/kernel/triton/flash_decoding.py
  tests/test_infer_ops/triton/kernel_utils.py
  tests/test_infer_ops/triton/test_context_attn_unpad.py
  tests/test_infer_ops/triton/test_decoding_attn.py
Labels: enhancement

#5261 [kernel] Add KV cache copy kernel during decoding
  colossalai/inference/modeling/layers/attention.py
  colossalai/kernel/triton/__init__.py
  colossalai/kernel/triton/kvcache_copy.py
  tests/test_infer_ops/triton/kernel_utils.py
  tests/test_infer_ops/triton/test_kvcache_copy.py
Labels: enhancement

#5274 [kernel/fix] Performance Optimization for Decoding Kernel
  colossalai/inference/modeling/models/llama.py
  colossalai/kernel/triton/__init__.py
  colossalai/kernel/triton/flash_decoding.py
  colossalai/kernel/triton/flash_decoding_utils.py
  tests/test_infer_ops/triton/kernel_utils.py
  tests/test_infer_ops/triton/test_context_attn_unpad.py
  tests/test_infer_ops/triton/test_decoding_attn.py
Labels: enhancement

#5292 [hotfix] fix 3d plugin test
  tests/test_booster/test_plugin/test_3d_plugin.py
Labels: bug

#5309 [moe] support mixtral
  applications/ColossalMoE/colossal_moe/models/mixtral_checkpoint.py
  applications/ColossalMoE/colossal_moe/models/mixtral_layer.py
  applications/ColossalMoE/colossal_moe/models/mixtral_policy.py
  applications/ColossalMoE/colossal_moe/utils.py
  applications/ColossalMoE/infer.py
  applications/ColossalMoE/tests/test_mixtral_layer.py
  applications/ColossalMoE/tests/test_moe_checkpoint.py
  applications/ColossalMoE/tests/test_moe_layer.py
  applications/ColossalMoE/train.py
  colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
  colossalai/checkpoint_io/checkpoint_io_base.py
  colossalai/moe/_operation.py
  colossalai/tensor/moe_tensor/moe_info.py
  colossalai/zero/low_level/low_level_optim.py
Labels: enhancement

#5314 [moe] fix mixtral checkpoint io
  applications/ColossalMoE/colossal_moe/models/mixtral_checkpoint.py
Labels: bug
