Repository hpcaitech/ColossalAI, pull requests merged in 2024-04, with the labels that each got.

#5565 [Inference/Spec-Dec] Add Speculative Decoding and GLIDE Spec-Dec
  colossalai/inference/README.md
  colossalai/inference/batch_bucket.py
  colossalai/inference/config.py
  colossalai/inference/core/engine.py
  colossalai/inference/core/request_handler.py
  colossalai/inference/kv_cache/kvcache_manager.py
  colossalai/inference/modeling/models/glide_llama.py
  colossalai/inference/modeling/models/nopadding_llama.py
  colossalai/inference/modeling/policy/__init__.py
  colossalai/inference/modeling/policy/glide_llama.py
  colossalai/inference/spec/README.md
  colossalai/inference/spec/__init__.py
  colossalai/inference/spec/drafter.py
  colossalai/inference/spec/struct.py
  colossalai/kernel/triton/__init__.py
  colossalai/kernel/triton/flash_decoding.py
  colossalai/kernel/triton/kvcache_copy.py
  tests/test_infer/test_drafter.py
  tests/test_infer/test_inference_engine.py
  tests/test_infer/test_ops/triton/kernel_utils.py
  tests/test_infer/test_ops/triton/test_decoding_attn.py
  tests/test_infer/test_ops/triton/test_kvcache_copy.py
Labels: enhancement

#5592 [shardformer] fix llama modeling
  colossalai/shardformer/modeling/bloom.py
  colossalai/shardformer/modeling/falcon.py
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/modeling/mistral.py
  colossalai/shardformer/modeling/opt.py
  colossalai/shardformer/modeling/t5.py
  colossalai/shardformer/modeling/vit.py
  colossalai/shardformer/modeling/whisper.py
  colossalai/shardformer/policies/mistral.py
Labels: bug

#5596 [zero] support multiple (partial) backward passes
  colossalai/zero/low_level/bookkeeping/bucket_store.py
  colossalai/zero/low_level/low_level_optim.py
  requirements/requirements.txt
Labels: enhancement

#5620 [shardformer] fix pipeline grad ckpt
  colossalai/shardformer/shard/grad_ckpt_config.py
  colossalai/shardformer/shard/shard_config.py
Labels: bug

#5626 [exampe] update llama example
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  examples/language/llama2/README.md
  examples/language/llama2/attn.py
  examples/language/llama2/benchmark.py
  examples/language/llama2/finetune.py
  examples/language/llama2/pretrain.py
  examples/language/llama2/requirements.txt
Labels: example

#5628 [shardformer] fix whisper
  colossalai/shardformer/modeling/whisper.py
  tests/kit/model_zoo/transformers/whisper.py
  tests/test_shardformer/test_model/test_shard_whisper.py
Labels: bug

#5629 [example] Update Llama Inference example
  colossalai/inference/modeling/policy/nopadding_llama.py
  examples/inference/benchmark_llama.py
  examples/inference/benchmark_llama3.py
  examples/inference/llama_generation.py
Labels: example

#5635 [test] fix llama model test
  tests/kit/model_zoo/transformers/llama.py
  tests/test_shardformer/test_model/test_shard_llama.py
Labels: bug, testing

#5644 [shardformer] fix chatglm implementation
  colossalai/pipeline/schedule/one_f_one_b.py
  colossalai/shardformer/README.md
  colossalai/shardformer/layer/normalization.py
  colossalai/shardformer/modeling/chatglm2.py
  colossalai/shardformer/policies/auto_policy.py
  colossalai/shardformer/policies/chatglm2.py
  docs/source/en/features/shardformer.md
  docs/source/zh-Hans/features/shardformer.md
  tests/kit/model_zoo/transformers/chatglm2.py
  tests/test_shardformer/test_model/_utils.py
  tests/test_shardformer/test_model/test_shard_chatglm2.py
Labels: shardformer

#5646 [shardformer] refactor pipeline grad ckpt config
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  colossalai/pipeline/stage_manager.py
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/modeling/mistral.py
  colossalai/shardformer/policies/base_policy.py
  colossalai/shardformer/shard/grad_ckpt_config.py
  colossalai/shardformer/shard/shard_config.py
  examples/language/llama/benchmark.py
  tests/test_pipeline/test_pipeline_utils/test_t5_pipeline_utils.py
  tests/test_pipeline/test_pipeline_utils/test_whisper_pipeline_utils.py
  tests/test_shardformer/test_model/test_shard_llama.py
Labels: shardformer

#5654 [release] update version
  version.txt
Labels: release

#5665 [devops] fix release docker ci
  .github/workflows/release_docker_after_publish.yml
Labels: bug, DevOps
