Repository hpcaitech/ColossalAI, pull requests merged in 2024-06, with the labels that each got.

#5780 [devops] fix docker ci
  .github/workflows/release_docker_after_publish.yml
Labels: DevOps

#5788 [shardformer] fix import
  colossalai/shardformer/modeling/llama.py
  colossalai/shardformer/modeling/qwen2.py
Labels: bug

#5771 [Inference] Refactor modeling attention layer by abstracting attention backends
  colossalai/inference/README.md
  colossalai/inference/config.py
  colossalai/inference/core/engine.py
  colossalai/inference/modeling/backends/__init__.py
  colossalai/inference/modeling/backends/attention_backend.py
  colossalai/inference/modeling/backends/pre_attention_backend.py
  colossalai/inference/modeling/models/nopadding_baichuan.py
  colossalai/inference/modeling/models/nopadding_llama.py
  colossalai/inference/modeling/policy/nopadding_baichuan.py
  colossalai/inference/modeling/policy/nopadding_llama.py
  colossalai/inference/utils.py
  tests/test_infer/test_kernels/cuda/test_flash_decoding_attention.py
  tests/test_infer/test_kernels/triton/test_context_attn_unpad.py
  tests/test_infer/test_kernels/triton/test_decoding_attn.py
  tests/test_infer/test_models/test_baichuan.py
Labels: colossal-inference

#5791 [Inference]refactor baichuan
  colossalai/inference/modeling/layers/baichuan_tp_linear.py
  colossalai/inference/modeling/models/nopadding_baichuan.py
  colossalai/inference/modeling/policy/nopadding_baichuan.py
Labels: colossal-inference

#5793 [test] fix chatglm test kit
  tests/kit/model_zoo/transformers/chatglm2.py
Labels: bug

#5796 [shardformer] fix modeling of bloom and falcon
  colossalai/shardformer/modeling/bloom.py
  colossalai/shardformer/modeling/falcon.py
Labels: bug

#5794 [Inference] Fix flash-attn import and add model test
  colossalai/inference/modeling/backends/attention_backend.py
  colossalai/inference/modeling/models/nopadding_baichuan.py
  colossalai/inference/modeling/models/nopadding_llama.py
  colossalai/inference/utils.py
  colossalai/shardformer/layer/attn.py
  tests/test_infer/test_kernels/cuda/test_kv_cache_memcpy.py
  tests/test_infer/test_models/test_custom_model.py
Labels: colossal-inference

#5835 [shardformer] Change atol in test command-r weight-check to pass 8GPU pytest
  tests/test_shardformer/test_model/test_shard_command.py
Labels: shardformer

#5837 [Fix] Fix spec-dec Glide LlamaModel for compatibility with transformers
  colossalai/inference/core/engine.py
  colossalai/inference/modeling/models/glide_llama.py
  colossalai/inference/spec/struct.py
  examples/inference/llama/README.md
Labels: colossal-inference

#5833 [release] update version
  version.txt
Labels: release

#5845 [gemini] fix missing return
  colossalai/zero/gemini/gemini_ddp.py
Labels: bug

#5860 [zero] use bucket during allgather
  colossalai/zero/low_level/bookkeeping/tensor_bucket.py
  colossalai/zero/low_level/low_level_optim.py
Labels: enhancement

#5785 [Inference]Lazy Init Support
  colossalai/inference/core/engine.py
  colossalai/inference/core/rpc_engine.py
  colossalai/inference/executor/rpc_worker.py
  colossalai/inference/modeling/layers/baichuan_tp_linear.py
  colossalai/inference/modeling/models/nopadding_baichuan.py
  colossalai/inference/modeling/models/nopadding_llama.py
  colossalai/shardformer/layer/qkv_fused_linear.py
Labels: colossal-inference

#5864 [release] update version
  version.txt
Labels: release
