Repository hpcaitech/ColossalAI, pull requests merged in 2024-09, with the labels that each got.

#6046 [fp8] fix linear hook
  colossalai/booster/plugin/hybrid_parallel_plugin.py
Labels: bug

#6041 [release] update version
  .github/workflows/compatiblity_test_on_dispatch.yml
  .github/workflows/compatiblity_test_on_pr.yml
  .github/workflows/compatiblity_test_on_schedule.yml
  .github/workflows/cuda_ext_check_before_merge.yml
  .github/workflows/doc_test_on_pr.yml
  .github/workflows/doc_test_on_schedule.yml
  .github/workflows/example_check_on_dispatch.yml
  .github/workflows/example_check_on_schedule.yml
  tests/test_infer/test_kernels/triton/test_fused_rotary_embedding.py
  version.txt
Labels: release

#6050 [doc] FP8 training and communication document
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
  colossalai/booster/plugin/torch_ddp_plugin.py
  docs/source/en/features/mixed_precision_training_with_booster.md
  docs/source/zh-Hans/features/mixed_precision_training_with_booster.md
Labels: documentation

#6056 [ColossalEval] support for vllm
  applications/ColossalEval/README.md
  applications/ColossalEval/colossal_eval/dataset/agieval.py
  applications/ColossalEval/colossal_eval/dataset/ceval.py
  applications/ColossalEval/colossal_eval/dataset/cmmlu.py
  applications/ColossalEval/colossal_eval/dataset/colossalai.py
  applications/ColossalEval/colossal_eval/dataset/cvalues.py
  applications/ColossalEval/colossal_eval/dataset/gaokaobench.py
  applications/ColossalEval/colossal_eval/dataset/gsm.py
  applications/ColossalEval/colossal_eval/dataset/longbench.py
  applications/ColossalEval/colossal_eval/dataset/mmlu.py
  applications/ColossalEval/colossal_eval/dataset/mtbench.py
  applications/ColossalEval/colossal_eval/dataset/safetybench_en.py
  applications/ColossalEval/colossal_eval/dataset/safetybench_zh.py
  applications/ColossalEval/colossal_eval/models/__init__.py
  applications/ColossalEval/colossal_eval/models/chatglm.py
  applications/ColossalEval/colossal_eval/models/huggingface.py
  applications/ColossalEval/colossal_eval/models/vllm.py
  applications/ColossalEval/examples/dataset_evaluation/inference.py
  applications/ColossalEval/requirements.txt
Labels: colossal-eval

#6062 [release] update version
  version.txt
Labels: release
