Repository hpcaitech/ColossalAI, pull requests merged in 2024-07, with the labels that each got.

#5879 [hotfix] fix the bug that large tensor exceed the maximum capacity of TensorBucket
  colossalai/zero/low_level/low_level_optim.py
Labels: bug

#5882 [quant] fix bitsandbytes version check
  colossalai/quantization/bnb.py
Labels: bug

#5838 [Feat] Refactor Engine and Diffusion Model(PixArtAlpha/StableDiffusion3) Support
  colossalai/inference/config.py
  colossalai/inference/core/base_engine.py
  colossalai/inference/core/diffusion_engine.py
  colossalai/inference/core/engine.py
  colossalai/inference/core/llm_engine.py
  colossalai/inference/core/request_handler.py
  colossalai/inference/modeling/models/diffusion.py
  colossalai/inference/modeling/models/pixart_alpha.py
  colossalai/inference/modeling/models/stablediffusion3.py
  colossalai/inference/modeling/policy/__init__.py
  colossalai/inference/modeling/policy/pixart_alpha.py
  colossalai/inference/modeling/policy/stablediffusion3.py
  colossalai/inference/struct.py
  colossalai/inference/utils.py
  examples/inference/stable_diffusion/sd3_generation.py
  requirements/requirements.txt
Labels: colossal-inference

#5892 [HotFix] CI,import,requirements-test for #5838
  colossalai/inference/core/llm_engine.py
  colossalai/inference/utils.py
  examples/inference/stable_diffusion/test_ci.sh
  requirements/requirements-test.txt
Labels: colossal-inference

#5912 [release] update version
  version.txt
Labels: release

#5895 [Feat] Distrifusion Acceleration Support for Diffusion Inference
  colossalai/inference/README.md
  colossalai/inference/config.py
  colossalai/inference/core/diffusion_engine.py
  colossalai/inference/modeling/layers/diffusion.py
  colossalai/inference/modeling/layers/distrifusion.py
  colossalai/inference/modeling/models/pixart_alpha.py
  colossalai/inference/modeling/models/stablediffusion3.py
  colossalai/inference/modeling/policy/pixart_alpha.py
  colossalai/inference/modeling/policy/stablediffusion3.py
  examples/inference/stable_diffusion/README.md
  examples/inference/stable_diffusion/benchmark_sd3.py
  examples/inference/stable_diffusion/compute_metric.py
  examples/inference/stable_diffusion/requirements.txt
  examples/inference/stable_diffusion/run_benchmark.sh
  examples/inference/stable_diffusion/sd3_generation.py
Labels: diffusion, colossal-inference

#5952 [release] update version
  version.txt
Labels: release
