Repository hpcaitech/ColossalAI, pull requests merged in 2024-10, with the labels that each got.

#6084 [shardformer] fix linear 1d row and support uneven splits for fused qkv linear
  colossalai/inference/modeling/policy/nopadding_baichuan.py
  colossalai/shardformer/layer/__init__.py
  colossalai/shardformer/layer/_operation.py
  colossalai/shardformer/layer/linear.py
  colossalai/shardformer/layer/qkv_fused_linear.py
  colossalai/shardformer/policies/blip2.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/sam.py
  tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
  tests/test_shardformer/test_layer/test_qkv_fused_linear_1d.py
Labels: bug, enhancement, shardformer

#6086 [shardformer] optimize seq parallelism
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/hybrid_parallel_plugin.py
  colossalai/booster/plugin/moe_hybrid_parallel_plugin.py
  colossalai/shardformer/layer/_operation.py
  colossalai/shardformer/layer/linear.py
  colossalai/shardformer/layer/qkv_fused_linear.py
  colossalai/shardformer/policies/bert.py
  colossalai/shardformer/policies/bloom.py
  colossalai/shardformer/policies/chatglm2.py
  colossalai/shardformer/policies/gpt2.py
  colossalai/shardformer/policies/gptj.py
  colossalai/shardformer/shard/shard_config.py
  tests/test_shardformer/test_layer/test_gpt2_qkv_fused_linear_1d.py
Labels: enhancement, shardformer

#6085 [Ring Attention] Improve comments & method arg naming
  colossalai/shardformer/layer/attn.py
  colossalai/shardformer/layer/utils.py
Labels: documentation

#6090 [pipeline] hotfix backward for multiple outputs
  colossalai/pipeline/schedule/interleaved_pp.py
  colossalai/pipeline/schedule/one_f_one_b.py
Labels: bug

#6094 [release] update version
  version.txt
Labels: release

#6099 [extension] hotfix compile check
  extensions/cpp_extension.py
  extensions/cuda_extension.py
Labels: bug

#6106 [checkpointio] fix hybrid plugin model save
  colossalai/checkpoint_io/hybrid_parallel_checkpoint_io.py
  colossalai/utils/__init__.py
  colossalai/utils/common.py
  colossalai/zero/gemini/gemini_ddp.py
Labels: bug
