Repository hpcaitech/ColossalAI, pull requests merged in 2025-01, with the labels that each got.

#6174 [release] update version
  .github/workflows/release_test_pypi_before_merge.yml
  version.txt
Labels: release

#6177 [checkpointio] support load-pin overlap
  colossalai/booster/plugin/gemini_plugin.py
  colossalai/booster/plugin/low_level_zero_plugin.py
  colossalai/booster/plugin/torch_fsdp_plugin.py
  colossalai/checkpoint_io/general_checkpoint_io.py
  colossalai/checkpoint_io/utils.py
  tests/conftest.py
Labels: enhancement

#6104 [Issue template] Add checkbox asking for details to reproduce error
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: DevOps
